// Static, shipped-with-the-app "tuning in" loading lines for every built-in station.
// These are baked into the source (not only generated at runtime) so they ALWAYS exist for
// built-ins and survive an uninstall/reinstall: reconcileBuiltins() re-applies them from here
// on every boot. User-created stations get their own set generated lazily by the LLM instead.
// Keyed by station id; each value is the rotating pool shown while a station spins up.

export const BUILTIN_TUNING_MESSAGES: Record<string, string[]> = {
  // ── Charts & essentials / Genres / Global ──────────────────────────────────────────
  'builtin:todays-hits': ['Cueing up the chart-toppers…', "Polishing this week's biggest hits…", 'Loading the freshest bangers…', 'Stacking the hottest tracks…', "Tuning into what's trending now…", "Spinning up today's number ones…"],
  'builtin:viral-hits': ['Loading the sounds you scrolled past…', 'Cueing up the for-you queue…', 'Catching the songs going viral…', 'Stacking the loops everyone knows…', "Spinning up tomorrow's earworms…", 'Refreshing the feed of bangers…'],
  'builtin:feel-good-classics': ['Warming up the sing-along section…', "Cueing up everybody's favorites…", 'Dusting off timeless crowd-pleasers…', "Loading hooks you can't forget…", 'Spinning up grin-worthy classics…', 'Stacking the feel-good favorites…'],
  'builtin:one-hit-wonders': ['Digging up that one perfect song…', 'Loading the tune you actually remember…', 'Cueing up unforgettable flukes…', 'Dusting off the lightning-bolt hits…', 'Spinning up beautiful accidents…', 'Stacking the songs over the names…'],
  'builtin:guilty-pleasures': ['Loading the songs you deny loving…', 'Cueing up the cheesy bangers…', 'Hiding the playlist, blasting it anyway…', 'Spinning up sweet musical sins…', 'Stacking unapologetic crowd-pleasers…', 'Warming up your secret favorites…'],
  'builtin:hip-hop-now': ['Loading the bars and beats…', 'Cueing up old school to new…', 'Dropping the freshest verses…', 'Stacking the heaviest 808s…', 'Spinning up the cypher…', 'Warming up the bounce…'],
  'builtin:classic-rock': ['Firing up the tube amps…', 'Loading the open-road anthems…', 'Cueing up timeless guitar solos…', 'Revving up the highway riffs…', 'Stacking the air-guitar classics…', 'Spinning up legendary licks…'],
  'builtin:throwback-rnb': ['Dimming the lights for slow jams…', 'Loading those 90s grooves…', 'Cueing up the silky throwbacks…', 'Warming up smooth 2000s vibes…', 'Spinning up late-night R&B…', 'Stacking the baby-making classics…'],
  'builtin:country-roads': ['Loading the road-trip anthems…', 'Cueing up modern and timeless twang…', 'Tuning up the steel guitar…', 'Stacking porch-swing favorites…', 'Spinning up dusty country gold…', 'Warming up the back roads…'],
  'builtin:jazz-cafe': ['Pouring the late-night standards…', 'Brewing smooth, easy jazz…', 'Dimming the café lights…', 'Letting the saxophone settle in…', 'Cueing up velvet midnight grooves…', 'Easing into the standards…'],
  'builtin:classical': ['Tuning the strings gently…', 'Easing into timeless masterworks…', 'Letting the orchestra settle…', 'Cueing up the great composers…', "Lifting the conductor's baton…", 'Drifting into iconic movements…'],
  'builtin:metal': ['Cranking the amps to eleven…', 'Loading the heaviest riffs…', 'Warming up the double-kick…', 'Stacking the headbangers…', 'Spinning up the wall of sound…', 'Sharpening the breakdowns…'],
  'builtin:punk': ['Counting in fast and loud…', 'Loading three chords and attitude…', 'Cueing up the rebellion…', 'Stacking the basement anthems…', 'Cranking the speed and snarl…', 'Spinning up sweaty mosh fuel…'],
  'builtin:funk-soul': ['Greasing up the basslines…', 'Loading the Motown gold…', 'Cueing up the groove…', 'Stacking the soulful struts…', 'Warming up the wah pedal…', 'Spinning up funky rhythms…'],
  'builtin:disco': ['Polishing the mirrorball…', 'Loading the dancefloor classics…', 'Cueing up the four-on-the-floor…', 'Warming up the strings and struts…', 'Stacking the boogie anthems…', 'Spinning up Saturday night fever…'],
  'builtin:blues': ['Dimming the smoky barroom…', 'Loading the soulful bends…', 'Plugging in the electric blues…', 'Cueing up the slow burners…', 'Warming up the twelve bars…', 'Spinning up the heartache…'],
  'builtin:folk-acoustic': ['Tuning the acoustic gently…', 'Settling in for the stories…', 'Letting the strumming begin…', 'Cueing up quiet songwriters…', 'Drifting into gentle harmonies…', 'Warming up the fireside tunes…'],
  'builtin:gospel': ['Warming up the choir…', 'Loading the uplifting voices…', 'Cueing up the spirit…', 'Stacking the hand-clap anthems…', 'Raising up soulful harmonies…', 'Spinning up joyful praise…'],
  'builtin:reggae': ['Easing into the island rhythm…', 'Loading the laid-back grooves…', 'Cueing up the offbeat skank…', 'Warming up the good vibes…', 'Settling into sunny basslines…', 'Spinning up irie tunes…'],
  'builtin:latin': ['Heating up the dancefloor…', 'Loading the salsa and pop…', 'Cueing up the brass and rhythm…', 'Stacking the hip-shaking hits…', 'Warming up the timbales…', 'Spinning up Latin fire…'],
  'builtin:reggaeton': ['Loading the dembow beat…', 'Cueing up the perreo…', 'Warming up the urban bangers…', 'Stacking the dancefloor heat…', 'Spinning up the party anthems…', 'Dropping the reggaetón fire…'],
  'builtin:kpop': ['Polishing the perfect hooks…', 'Loading the group anthems…', 'Cueing up the synced choreo…', 'Stacking the glossy bangers…', 'Warming up the comeback stage…', 'Spinning up the fandom favorites…'],
  'builtin:afrobeats': ['Warming up the West African rhythm…', 'Loading the global bangers…', 'Cueing up the smooth grooves…', 'Stacking the log-drum beats…', 'Spinning up sunny dancefloor vibes…', 'Easing into the bounce…'],
  'builtin:electronic-pulse': ['Charging up the synths…', 'Loading the house and techno…', 'Cueing up the four-on-the-floor pulse…', 'Building the drop…', 'Stacking the EDM energy…', 'Spinning up the rave…'],
  'builtin:synthwave': ['Lighting up the neon grid…', 'Loading the retro-future drive…', 'Cueing up the analog synths…', 'Warming up the 80s glow…', 'Stacking the midnight cruise…', 'Spinning up the chrome dreams…'],

  // ── Indie / Decades / Moods & activities / Fun & themed ─────────────────────────────
  'builtin:indie-discoveries': ['Crate-digging for dream-pop gems…', 'Tuning the reverb haze…', "Unearthing tomorrow's favorite band…", 'Stringing up jangly guitars…', 'Threading hazy hooks together…', 'Discovering your next obsession…'],
  'builtin:alt-2000s': ['Cueing up the angst anthems…', 'Plugging in the distortion pedals…', 'Reviving the early-2000s alt fire…', 'Rounding up radio rebels…', 'Stacking emo-era bangers…', 'Dialing the alternative nation in…'],
  'builtin:golden-oldies': ['Polishing the jukebox chrome…', 'Lacing up your dancing shoes…', 'Spinning sock-hop forty-fives…', 'Slicking back the doo-wop…', 'Setting the malt-shop mood…', 'Cueing those golden harmonies…'],
  'builtin:70s-gold': ['Sliding into your disco boots…', 'Greasing up the funk grooves…', 'Mellowing out the soft rock…', 'Lighting the mirrorball glow…', 'Feathering out the seventies gold…', 'Laying down silky basslines…'],
  'builtin:80s-throwback': ['Cranking the neon synths…', 'Teasing up the hair metal…', 'Loading cassette decks with hits…', 'Blasting the gated reverb drums…', 'Powering up the pop icons…', 'Rewinding to the eighties…'],
  'builtin:90s-nostalgia': ['Tuning up the grunge fuzz…', 'Cueing boy-band harmonies…', 'Dropping the nineties hip-hop…', 'Flannel on, amps loud…', 'Rewinding the cassette nostalgia…', 'Stacking ninety-decade classics…'],
  'builtin:2000s-throwback': ['Calling up the TRL countdown…', 'Lacing the pop-punk laces…', 'Turning the crunk up loud…', 'Loading flip-phone ringtone hits…', 'Cueing the early-aughts bangers…', 'Throwing back to two-thousands…'],
  'builtin:workout': ['Loading the high-energy fuel…', 'Cranking your pump-up anthems…', 'Pacing your next personal best…', 'Spinning up beats-per-rep…', 'Powering through the warm-up…', 'Charging the gym adrenaline…'],
  'builtin:party': ['Filling the room with bangers…', 'Cueing the crowd-pleasers…', 'Cranking the dance floor up…', 'Loading hands-in-the-air hits…', 'Pouring out the party fuel…', 'Getting everybody moving…'],
  'builtin:roadtrip': ['Rolling the windows down…', 'Cueing the singalong anthems…', 'Mapping out the highway hits…', 'Fueling up for the drive…', 'Loading open-road classics…', 'Setting the cruise control…'],
  'builtin:deep-focus': ['Settling into quiet concentration…', 'Smoothing out the calm instrumentals…', 'Clearing space for deep work…', 'Easing the mind into focus…', 'Tuning the gentle background flow…', 'Softening the world away…'],
  'builtin:lofi-focus': ['Brewing some chilled study beats…', 'Crackling the warm vinyl hiss…', 'Easing into mellow lo-fi…', 'Looping the cozy boom-bap…', 'Softening the rainy-window grooves…', 'Settling in to focus…'],
  'builtin:chill': ['Easing into laid-back vibes…', 'Unwinding the mellow grooves…', 'Softening the evening mood…', 'Letting the tempo settle…', 'Pouring out the calm…', 'Kicking your feet up…'],
  'builtin:sleep': ['Dimming the lights softly…', 'Drifting toward gentle quiet…', 'Hushing the room to calm…', 'Folding the day to rest…', 'Soft sounds settling in…', 'Easing you toward sleep…'],
  'builtin:meditation': ['Settling into still silence…', 'Easing the breath gently…', 'Unrolling the calm mat…', 'Letting serene tones bloom…', 'Softening into the present…', 'Finding your quiet center…'],
  'builtin:rainy-day': ['Steeping a warm cup…', 'Pulling the cozy blanket close…', 'Tracing raindrops down the window…', 'Softening the gray afternoon…', 'Settling into melancholy comfort…', 'Letting the rain hum…'],
  'builtin:morning-coffee': ['Pouring the first warm cup…', 'Easing into a bright morning…', 'Letting the sunrise filter in…', 'Stirring gentle morning tunes…', 'Brewing a soft start…', 'Greeting the day softly…'],
  'builtin:coffeehouse': ['Tuning the acoustic strings…', 'Pulling up a corner stool…', 'Brewing some unplugged covers…', 'Strumming a quiet ballad…', 'Settling into the open mic…', 'Warming up the songwriter set…'],
  'builtin:date-night': ['Lighting the candles low…', 'Pouring two glasses softly…', 'Smoothing out the romance…', 'Dimming into the slow groove…', 'Setting the candlelit mood…', 'Cueing the love songs…'],
  'builtin:dinner-party': ['Setting the sophisticated table…', 'Pouring the smooth background grooves…', "Uncorking the evening's mood…", 'Plating up subtle vibes…', 'Dimming into elegant ambiance…', 'Letting conversation glide…'],
  'builtin:retro-gaming': ['Blowing dust off the cartridge…', 'Cueing the classic chiptunes…', 'Loading the level-one theme…', 'Inserting coin for tunes…', 'Powering up the old console…', 'Pressing start on nostalgia…'],
  'builtin:8bit-chiptune': ['Squaring up the bleeps…', 'Loading fresh chiptune tracks…', 'Tuning the pulse-wave channels…', 'Sequencing crisp 8-bit beats…', 'Powering the modern chip scene…', 'Stacking pixel-perfect melodies…'],
  'builtin:vgm-remixes': ['Orchestrating epic game themes…', 'Remixing the boss-fight anthems…', 'Layering up grand arrangements…', 'Powering up legendary motifs…', 'Reimagining classic soundtracks…', 'Cueing the heroic remixes…'],
  'builtin:game-soundtracks': ['Swelling the cinematic strings…', 'Loading the modern game scores…', 'Cueing the sweeping orchestra…', 'Setting the epic atmosphere…', 'Rendering the soundtrack in full…', 'Lifting the heroic theme…'],
  'builtin:vaporwave': ['Slowing the tempo to dreamy…', 'Drifting through the retro mall…', 'Bathing in neon nostalgia…', 'Stretching the tape warmly…', 'Floating into pastel haze…', 'Easing into the aesthetic…'],

  // ── Movies / TV & nostalgia / More party ────────────────────────────────────────────
  'builtin:movie-scores': ['Cueing the overture…', 'Raising the orchestra pit…', 'Dimming the house lights…', 'Tuning the sweeping strings…', 'Threading the film reel…', 'Conducting the opening swell…'],
  'builtin:anime': ['Cuing the opening sequence…', 'Spinning up J-pop bangers…', 'Loading the next OP…', 'Rolling the ending credits…', 'Powering up the playlist…', 'Drawing in the bass drop…'],
  'builtin:yacht-rock': ['Casting off the smooth sails…', 'Pouring a breezy groove…', 'Hoisting the soft-rock mainsail…', 'Catching that mellow trade wind…', 'Polishing the brass solo…', 'Drifting into golden hour…'],
  'builtin:halloween': ['Summoning the spooky setlist…', 'Creaking open the crypt…', 'Lighting the jack-o-lanterns…', 'Stirring the eerie cauldron…', 'Loosing the howling winds…', 'Cueing the midnight chimes…'],
  'builtin:holiday': ['Stringing up the twinkle lights…', 'Warming the cocoa playlist…', 'Hanging festive stockings…', 'Jingling the sleigh bells…', 'Trimming the cozy tree…', 'Cueing the chestnut roast…'],
  'builtin:80s-tv-themes': ['Tuning the rabbit ears…', 'Cueing the synth fanfare…', 'Warming up the VCR…', 'Rolling the prime-time intro…', 'Loading the neon credits…', 'Spinning that catchy hook…'],
  'builtin:90s-tv-themes': ['Cuing the sitcom couch…', 'Loading the cartoon opener…', 'Spinning the laugh-track theme…', 'Rolling the Saturday lineup…', 'Warming up the boombox…', 'Dialing in the catchy hook…'],
  'builtin:tv-greatest-themes': ['Cueing the channel surf…', 'Loading unforgettable openers…', 'Rolling decades of credits…', 'Spinning the iconic hooks…', 'Warming up the small screen…', 'Dialing in primetime gold…'],
  'builtin:saturday-cartoons': ['Pouring the cereal bowl…', 'Cueing the morning toons…', 'Loading the cartoon credits…', "Spinning Saturday's lineup…", 'Warming up the TV set…', 'Rolling the animated intro…'],
  'builtin:disney-animated': ['Cueing the sing-along magic…', 'Sprinkling pixie dust…', 'Loading the storybook reel…', 'Warming up the chorus…', 'Lighting the castle spires…', 'Rolling the animated overture…'],
  'builtin:broadway': ['Raising the velvet curtain…', 'Cueing the orchestra pit…', 'Warming up the spotlight…', 'Loading the showstopper…', 'Dimming the marquee lights…', 'Tuning the eleven-o-clock number…'],
  'builtin:90s-nick': ['Cueing the slime drop…', 'Loading the Nick opener…', 'Spinning the orange logo…', 'Warming up the splat…', 'Rolling the after-school theme…', 'Dialing in the catchy intro…'],
  'builtin:2k-nick': ['Cueing the millennium opener…', 'Loading the Nick theme…', 'Spinning the green slime…', 'Warming up the splat logo…', 'Rolling the after-school hook…', 'Dialing in the catchy intro…'],
  'builtin:disney-channel': ['Drawing the mouse-ear wand…', 'Cueing the DCOM opener…', 'Loading the channel hits…', 'Warming up the sing-along…', 'Spinning the bop of summer…', 'Rolling the theme-song magic…'],
  'builtin:cartoon-network': ['Cueing the Toonami countdown…', 'Loading the CN opener…', 'Spinning the action block…', 'Warming up the bumpers…', 'Rolling the cartoon intro…', 'Dialing in the late-night vibe…'],
  'builtin:2010s-throwback': ['Cueing the EDM drop…', 'Loading the indie anthem…', 'Spinning the throwback feels…', 'Warming up the festival lights…', 'Rolling the pop-banger queue…', 'Dialing in the nostalgia…'],
  'builtin:summer-beach': ['Catching the warm sea breeze…', 'Pouring the sunshine playlist…', 'Loading the beach towels…', 'Spinning breezy summer vibes…', 'Warming up the boardwalk…', 'Drifting into golden sand…'],
  'builtin:motown-gold': ['Cueing the velvet groove…', 'Loading the young America sound…', 'Spinning the golden soul…', 'Warming up the horn section…', 'Rolling the foot-tapping rhythm…', 'Dialing in that Detroit shine…'],
  'builtin:karaoke': ['Handing out the microphone…', 'Cueing the bouncing lyrics…', 'Warming up your vocal cords…', 'Loading the crowd anthems…', 'Spinning the belt-it-out hits…', 'Lighting the karaoke stage…'],
  'builtin:wedding': ['Clearing the dance floor…', 'Cueing the first-dance song…', 'Loading the floor-fillers…', 'Warming up the reception…', 'Spinning the crowd anthems…', 'Lighting the celebration lights…'],
  'builtin:pride-anthems': ['Raising the rainbow flag…', 'Cueing the dancefloor empowerment…', 'Loading the celebration anthems…', 'Warming up the disco lights…', 'Spinning the proud parade…', 'Lighting the glitter cannon…'],
  'builtin:bollywood': ['Cueing the vibrant dhol beat…', 'Loading the cinema spectacle…', 'Warming up the dance number…', 'Spinning the colorful hits…', 'Rolling the silver-screen magic…', 'Dialing in the festive rhythm…'],
  'builtin:movie-soundtracks': ['Cueing the iconic needle-drop…', 'Threading the film reel…', 'Loading the soundtrack hits…', 'Warming up the big screen…', 'Spinning the on-screen anthems…', 'Rolling the closing credits…'],
  'builtin:80s-movies': ['Cueing the John Hughes montage…', 'Loading the Brat Pack anthems…', 'Warming up the boombox…', 'Spinning the neon-soaked hits…', 'Rolling the prom-night theme…', 'Dialing in the synth nostalgia…'],
  'builtin:james-bond': ['Loading the gun-barrel sequence…', 'Cueing the sultry brass swell…', 'Pouring the martini…', 'Warming up the spy strings…', 'Spinning the 007 title song…', 'Dialing in the secret-agent groove…'],

  // ── More movies / nostalgia / popular ───────────────────────────────────────────────
  'builtin:tarantino': ['Cueing the cult-classic vinyl…', 'Slicking back the retro grooves…', 'Dusting off forgotten soundtrack gems…', 'Loading the trunk-shot cool…', 'Spinning up surf-guitar swagger…', 'Lighting the diner jukebox…'],
  'builtin:spaghetti-western': ['Saddling up the lonesome whistle…', 'Kicking dust across the frontier…', 'Tuning the twangy duel guitar…', 'Loading the high-noon standoff…', 'Letting the trumpet ride out…', 'Squinting toward the dusty horizon…'],
  'builtin:sci-fi-scores': ['Booting the otherworldly synths…', 'Charging the warp-drive strings…', 'Drifting through nebula soundscapes…', 'Opening the airlock of sound…', 'Beaming down alien frequencies…', 'Igniting the cosmic overture…'],
  'builtin:horror-scores': ['Creaking open the cellar door…', 'Letting the strings start screaming…', 'Dimming the lights, slowly…', 'Stirring something in the dark…', 'Whispering down the empty hall…', 'Winding the music box backward…'],
  'builtin:rom-com': ['Cueing the airport-dash anthem…', 'Falling for the perfect melody…', 'Loading the meet-cute soundtrack…', 'Stringing up fairy-light feelings…', 'Setting the swoon to music…', 'Pressing play on happily-ever-after…'],
  'builtin:training-montage': ['Lacing up the gym sneakers…', 'Cueing the staircase sprint…', 'Punching the heavy bag warm…', 'Building that unstoppable beat…', 'Climbing toward the big fight…', 'Pushing past the burn now…'],
  'builtin:superhero-themes': ['Charging the heroic brass section…', 'Raising the cape to wind…', 'Loading the blockbuster orchestra…', 'Igniting the call to courage…', 'Soaring the strings sky-high…', 'Suiting up for the anthem…'],
  'builtin:british-invasion': ['Tuning the Liverpool guitars…', 'Loading the mod-era jangle…', 'Stepping into the swinging sixties…', 'Mopping up the harmonies…', 'Crossing the pond with hooks…', 'Spinning the 45s now…'],
  'builtin:hair-metal': ['Teasing the hair sky-high…', 'Plugging in the screaming solos…', 'Loading the spandex swagger…', 'Cranking the Sunset Strip riffs…', 'Spraying on the 80s shine…', 'Lighting the pyro now…'],
  'builtin:new-wave': ['Booting the moody synthesizers…', 'Loading the art-school cool…', 'Painting the night neon…', 'Cueing the angular guitars…', 'Skinny ties going on…', 'Pulsing the 80s drum machine…'],
  'builtin:grunge': ['Pulling on the flannel…', 'Tuning the muddy distortion…', 'Loading the Seattle drizzle…', 'Cranking the basement amps…', 'Slacking into the riffs…', 'Letting the feedback howl…'],
  'builtin:golden-age-hiphop': ['Digging the dusty crates…', 'Loading the boom-bap breaks…', 'Cueing the gritty samples…', 'Cutting up the vinyl…', 'Dropping the 90s knowledge…', 'Warming the MPC pads…'],
  'builtin:boy-bands-divas': ['Cueing the choreographed harmonies…', 'Loading the late-90s sparkle…', 'Hitting the whistle-note high…', 'Synchronizing the dance moves…', 'Polishing the pop royalty…', 'Dropping the key change…'],
  'builtin:power-ballads': ['Raising the lighters slowly…', 'Building toward the huge chorus…', 'Loading the emotional crescendo…', 'Letting the solo soar…', 'Swaying the whole arena…', 'Holding that final note…'],
  'builtin:stadium-anthems': ['Filling the arena with sound…', 'Cueing the crowd to roar…', 'Loading the fist-pump riffs…', 'Stomping out the big beat…', 'Lighting the whole stadium up…', 'Cranking the singalong chorus…'],
  'builtin:outlaw-country': ['Saddling the rugged road songs…', 'Pouring the whiskey-soaked twang…', 'Loading the rebel hearts…', 'Dusting off the worn boots…', 'Lighting the campfire low…', 'Riding off the beaten path…'],
  'builtin:singer-songwriter-70s': ['Tuning the warm acoustic strings…', 'Loading the confessional whispers…', 'Pulling up the quiet stool…', 'Softening the candlelit verses…', 'Pouring the intimate melodies…', 'Settling into the gentle hush…'],
  'builtin:y2k-pop': ['Loading the bubblegum sparkle…', 'Flipping open the millennium hits…', 'Cueing the frosted-tip choruses…', 'Spinning the turn-of-century shine…', 'Charging the candy-coated beats…', 'Pressing play on Y2K…'],
  'builtin:happy-vibes': ['Letting the sunshine pour in…', 'Loading the pure good moods…', 'Cueing the carefree melodies…', 'Brightening the whole room…', 'Skipping into the bouncy beat…', 'Spreading the warm grins…'],
  'builtin:in-my-feels': ['Settling into the big feelings…', 'Loading the tender heartstrings…', 'Dimming into soft emotion…', 'Letting the quiet ache build…', 'Cueing the lump-in-throat melody…', 'Holding space for feelings…'],
  'builtin:heartbreak': ['Cueing the good cry…', 'Loading the breakup ballads…', 'Pouring out the aching chorus…', 'Softening into the sad strings…', 'Letting the tears flow…', 'Stirring the bittersweet ache…'],
  'builtin:confidence': ['Loading the boss-mode swagger…', 'Cueing the head-held-high anthem…', 'Charging the empowerment energy…', 'Strutting into the beat…', 'Owning the whole room…', 'Turning up the self-belief…'],
  'builtin:rage': ['Cranking the angry distortion…', 'Loading the let-it-out roar…', 'Cueing the pounding fury…', 'Building the breaking-point beat…', 'Unleashing the loud release…', 'Screaming into the riffs…'],
  'builtin:euphoric': ['Building toward the blissful drop…', 'Loading the soaring dancefloor highs…', 'Charging the rush of light…', 'Lifting the room skyward…', 'Cueing the hands-up euphoria…', 'Floating into the glow…'],
  'builtin:dreamy': ['Drifting into the soft haze…', 'Loading the ethereal shimmer…', 'Floating through the gentle clouds…', 'Blurring the edges of sound…', 'Cueing the weightless reverb…', 'Slipping into the dream…'],

  // ── Moods / Eras / Classic genres & deep cuts ───────────────────────────────────────
  'builtin:moody': ['Dimming the lights low…', 'Stirring the midnight shadows…', 'Pouring something brooding and dark…', 'Letting the fog roll in…', 'Tuning the after-hours hum…', 'Loading reverb-soaked melancholy…'],
  'builtin:mellow-mood': ['Kicking back the tempo…', 'Settling into easy grooves…', 'Softening every edge slowly…', 'Loading low-key warmth…', 'Letting the day unwind…', 'Cueing something gently mellow…'],
  'builtin:sensual': ['Lowering the lights softly…', 'Slipping into something smoother…', 'Letting the slow jams simmer…', 'Warming the bedroom groove…', 'Drawing the curtains low…', 'Easing into sultry rhythm…'],
  'builtin:motivation': ['Locking in the drive…', 'Building a steady pulse…', 'Charging up the focus…', 'Loading momentum, no distractions…', 'Setting the pace forward…', 'Tightening every beat tight…'],
  'builtin:good-times': ['Rolling the windows down…', 'Stirring up breezy vibes…', 'Loading sunshine and good company…', 'No worries on deck…', 'Cueing carefree summer grooves…', 'Letting the good times roll…'],
  'builtin:jazz-age': ['Polishing the brass horns…', 'Winding up the ragtime piano…', 'Loading speakeasy swing…', 'Dusting off the gramophone…', 'Cueing the Charleston shuffle…', 'Pouring some roaring twenties jazz…'],
  'builtin:big-band': ['Lining up the horn section…', 'Counting in the swing…', 'Polishing the dance floor brass…', 'Loading that 1940s bounce…', "Cueing the bandleader's baton…", 'Warming up the trombones…'],
  'builtin:flower-power': ['Loading peace and patchouli…', 'Stringing up the love beads…', 'Cueing the psychedelic swirl…', 'Letting the daisies bloom…', 'Tuning the counterculture jangle…', 'Drifting into sixties dreams…'],
  'builtin:2020s-now': ['Loading the freshest drops…', "Cueing this decade's pulse…", 'Streaming what’s hot now…', 'Spinning the latest sound…', "Catching today's chart heat…", 'Loading right-now anthems…'],
  'builtin:southern-rock': ['Firing up the twang…', 'Loading some boogie guitar…', 'Pouring sweet tea licks…', 'Cueing the slide guitar jam…', 'Letting the riffs ramble…', 'Warming up the front porch…'],
  'builtin:prog-rock': ['Loading the concept album…', 'Building the epic suite…', 'Tuning the odd time signatures…', 'Cueing a twenty-minute journey…', 'Stacking the synth layers…', 'Setting the cosmos in motion…'],
  'builtin:psychedelic-rock': ['Bending the soundscape sideways…', 'Loading the kaleidoscope groove…', 'Soaking the riffs in echo…', 'Cueing the mind-melting trip…', 'Swirling the technicolor haze…', 'Tuning into other dimensions…'],
  'builtin:surf-rock': ['Drenching the strings in reverb…', 'Waxing up the surfboard…', 'Loading the beach instrumentals…', 'Catching that perfect wave…', 'Cueing the twangy shoreline…', 'Riding the reverb tide…'],
  'builtin:rockabilly': ['Slapping the upright bass…', 'Greasing up the pompadour…', 'Loading that fifties bop…', 'Cueing the rebel twang…', 'Revving the hot-rod rhythm…', 'Kicking up the jukebox…'],
  'builtin:glam-rock': ['Dusting on the glitter…', 'Loading the stomping swagger…', 'Strutting in platform boots…', 'Cueing the seventies sparkle…', 'Cranking the flashy riffs…', 'Warming up the spotlight…'],
  'builtin:britpop': ['Loading the UK swagger…', 'Cueing the jangly guitars…', 'Pouring some ninety-five attitude…', 'Tuning the Manchester strut…', 'Warming up the singalong…', 'Setting the lads in motion…'],
  'builtin:ska': ['Tightening the upstroke skank…', 'Warming up the brass…', 'Loading the offbeat bounce…', 'Cueing the rocksteady groove…', 'Skanking into the rhythm…', 'Pouring some sunny upstrokes…'],
  'builtin:bluegrass': ['Rolling up the banjo…', 'Tuning the high lonesome harmony…', 'Loading the front-porch picking…', 'Cueing the fiddle breakdown…', 'Warming up the mandolin…', 'Stringing the bluegrass barn dance…'],
  'builtin:nu-metal': ['Downtuning the seven-string…', 'Loading the angsty crunch…', 'Cueing the two-thousands rage…', 'Cranking the heavy riffs…', 'Warming up the scratch turntables…', 'Building the bounce-pit fury…'],
  'builtin:new-jack-swing': ['Programming the swing beat…', 'Loading the new jack groove…', 'Cueing that early-nineties bounce…', 'Layering the slick harmonies…', 'Warming up the drum machine…', 'Setting the smooth swagger…'],
  'builtin:smooth-jazz': ['Pouring something silky and warm…', 'Easing the sax in…', 'Loading the late-night smooth…', 'Letting the keys glide…', 'Settling into mellow grooves…', 'Drifting into easygoing jazz…'],
}
