"""Build the global low-zoom ``world-overview.pmtiles`` basemap.

The regional ``streets.pmtiles`` generated by ``building_streets`` only
carries tiles for (x, y) cells that intersect the region's bbox. At low
zoom (z0–z7) the user can pan/zoom anywhere on the globe, so the style
needs a second source that always has something to paint — country +
state polygons, ocean fill, country/state labels. This preflight
produces that second source **once**, during bootstrap, so the runtime
can point a MapLibre source at a local file instead of a remote tile
CDN.

Mechanism — the "Monaco hack"
-----------------------------
planetiler's OpenMapTiles profile requires an OSM input file. It does
not expose a "Natural Earth only" mode. But the profile emits Natural
Earth features globally at low zoom regardless of the OSM extent. So
we pass the smallest Geofabrik extract we can find (Monaco, ~800 KB),
cap output at z7, and accept the ~2 km² of Monaco streets that bleeds
into the global tileset. Alternative (custom NE-only planetiler
profile) would require shipping a compiled Java plugin — rejected.

Layout after install::

    .lokidoki/tools/planetiler/
        sources/monaco-latest.osm.pbf       # throwaway OSM input
        world-overview.pmtiles              # ~20–50 MB global z0–z7 basemap

The planetiler download flag is intentionally NOT passed — the three
source files (Monaco PBF, Natural Earth sqlite, OSM water polygons)
are all materialised by earlier preflights, so planetiler must read
them locally. This matches the offline-hardening rule established
by ``install-planetiler-data`` + chunk 2 of the offline-hardening
plan.
"""
from __future__ import annotations

import logging
import os
from pathlib import Path

from ..context import StepContext
from ..events import StepLog
from ..versions import MONACO_PBF, NATURAL_EARTH, OSM_WATER_POLYGONS


_log = logging.getLogger(__name__)
_STEP_ID = "build-world-overview"

# planetiler's OpenMapTiles profile emits Natural Earth features up to
# z7 regardless of OSM extent — pin the cap here so the "throwaway
# Monaco streets" bleed stays bounded.
_MAX_ZOOM = 7

# planetiler derives output bounds from the OSM input when ``--bounds``
# is omitted. With Monaco as the OSM input that means the NE + water
# polygons also get clipped to Monaco's ~2 km² bbox, producing a ~45 KB
# pmtiles with zero global coverage. Pass an explicit world bbox so NE
# fills the whole planet. ``85`` as the lat cap matches Web Mercator's
# singularity at ±85.0511° — planetiler projects at that range anyway.
_WORLD_BOUNDS = "-180,-85,180,85"

# Heap budget for the world-overview build. NE + water polygons need
# room to page through the sqlite index and the water-polygons zip
# index, so start with 2 GiB. An env override is accepted for the rare
# tight-memory Pi case (though Pi profiles skip this build on disk
# anyway).
_HEAP_MB_DEFAULT = 2048
_HEAP_MB_ENV = "LOKIDOKI_WORLD_OVERVIEW_HEAP_MB"

# Smoke thresholds. Anything under 1 MB on an existing file is almost
# certainly a truncated or aborted previous run — re-build. Anything
# under 5 MB on a fresh build is corrupt — delete + raise.
_SKIP_MIN_BYTES = 1 * 1024 * 1024
_SMOKE_MIN_BYTES = 5 * 1024 * 1024


async def ensure_world_overview(ctx: StepContext) -> None:
    """Build ``world-overview.pmtiles`` if missing.

    Short-circuits when the target file exists and is above the skip
    threshold. Otherwise downloads the Monaco PBF (if needed) and runs
    planetiler with explicit source paths + ``--maxzoom=7``.
    """
    out_pmtiles = ctx.binary_path("world_overview_pmtiles")
    if _present_above(out_pmtiles, _SKIP_MIN_BYTES):
        ctx.emit(
            StepLog(
                step_id=_STEP_ID,
                line=(
                    f"world-overview pmtiles already present at {out_pmtiles} "
                    f"({out_pmtiles.stat().st_size} bytes)"
                ),
            )
        )
        return

    java_bin = ctx.binary_path("java")
    jar_path = ctx.binary_path("planetiler_jar")
    sources_dir = ctx.binary_path("planetiler_sources")
    _require_exists(java_bin, "java")
    _require_exists(jar_path, "planetiler.jar")
    _require_exists(sources_dir, "planetiler sources directory")

    # 1. Make sure Monaco is on disk — download if missing, verify sha.
    monaco_path = sources_dir / MONACO_PBF["filename"]
    if not _present_above(monaco_path, 1):
        url = MONACO_PBF["url_template"].format(filename=MONACO_PBF["filename"])
        ctx.emit(
            StepLog(step_id=_STEP_ID, line=f"downloading monaco pbf: {url}")
        )
        await ctx.download(url, monaco_path, _STEP_ID, sha256=MONACO_PBF["sha256"])

    # 2. Run planetiler with explicit per-file paths and --maxzoom=7.
    natural_earth = sources_dir / NATURAL_EARTH["filename"]
    water_polygons = sources_dir / OSM_WATER_POLYGONS["filename"]
    _require_exists(natural_earth, "natural earth sqlite")
    _require_exists(water_polygons, "osm water polygons")

    out_pmtiles.parent.mkdir(parents=True, exist_ok=True)
    scratch = out_pmtiles.with_name(
        f"{out_pmtiles.stem}.partial{out_pmtiles.suffix}"
    )
    if scratch.exists():
        scratch.unlink()

    heap_mb = _heap_mb()
    cmd = [
        str(java_bin),
        f"-Xmx{heap_mb}m",
        "-jar",
        str(jar_path),
        f"--osm-path={monaco_path}",
        f"--natural_earth_path={natural_earth}",
        f"--water_polygons_path={water_polygons}",
        f"--output={scratch}",
        f"--maxzoom={_MAX_ZOOM}",
        f"--bounds={_WORLD_BOUNDS}",
        "--force",
    ]
    ctx.emit(
        StepLog(
            step_id=_STEP_ID,
            line=(
                "running planetiler: "
                f"heap={heap_mb}m maxzoom={_MAX_ZOOM} -> {out_pmtiles.name}"
            ),
        )
    )
    rc = await ctx.run_streamed(cmd, _STEP_ID)
    if rc != 0:
        if scratch.exists():
            scratch.unlink()
        raise RuntimeError(
            f"planetiler exited {rc} while building world-overview.pmtiles"
        )

    # 3. Smoke test: fresh build must be at least _SMOKE_MIN_BYTES bytes.
    if not scratch.exists() or scratch.stat().st_size < _SMOKE_MIN_BYTES:
        size = scratch.stat().st_size if scratch.exists() else 0
        if scratch.exists():
            scratch.unlink()
        raise RuntimeError(
            f"world-overview.pmtiles suspiciously small ({size} bytes) — "
            "treating build as corrupt; re-run bootstrap to retry"
        )

    if out_pmtiles.exists():
        out_pmtiles.unlink()
    scratch.replace(out_pmtiles)

    ctx.emit(
        StepLog(
            step_id=_STEP_ID,
            line=(
                f"world-overview pmtiles ready at {out_pmtiles} "
                f"({out_pmtiles.stat().st_size} bytes)"
            ),
        )
    )


def _present_above(path: Path, threshold: int) -> bool:
    return path.exists() and path.is_file() and path.stat().st_size >= threshold


def _require_exists(path: Path, label: str) -> None:
    if not path.exists():
        raise RuntimeError(
            f"{label} missing at {path} — re-run ./run.sh --maps-tools-only "
            "so the upstream preflights seed it before building the "
            "world overview basemap"
        )


def _heap_mb() -> int:
    raw = os.environ.get(_HEAP_MB_ENV, "").strip()
    if raw:
        try:
            value = int(raw)
        except ValueError:
            _log.warning("ignoring invalid %s=%r", _HEAP_MB_ENV, raw)
        else:
            if value > 0:
                return value
            _log.warning("ignoring non-positive %s=%r", _HEAP_MB_ENV, raw)
    return _HEAP_MB_DEFAULT


