// OS-install fingerprint — detects "the OS drive was wiped/reinstalled but data/
// survived" as a certain signal instead of inferring it from how many components
// happen to be missing. We stamp the identity of the *OS install* (not the
// hardware) into data/.os-fingerprint; when the stamp stops matching, the OS was
// reinstalled and boot flips reconcile into restore mode (routes/system.ts).
//
// The stamp is written AFTER reconcile has recorded the restore plan, so a crash
// mid-boot re-detects the change on the next boot rather than losing the signal.

import { execFile } from 'node:child_process'
import { promisify } from 'node:util'
import { readFile, writeFile } from 'node:fs/promises'
import { join } from 'node:path'
import { dataDir } from '@/lib/download'
import { logger } from '@/lib/logger'

const execFileAsync = promisify(execFile)

const FINGERPRINT_FILE = join(dataDir, '.os-fingerprint')

export type OsFingerprintStatus =
  | 'first-stamp'  // no fingerprint on disk yet (fresh install, or feature just shipped)
  | 'match'        // same OS install as last boot
  | 'changed'      // OS was reinstalled under us — data/ survived, system drive didn't
  | 'unknown'      // could not determine an OS identity on this platform

interface StoredFingerprint {
  osId: string
  platform: string
  recordedAt: string
}

/** Identity of the current OS *install* — regenerated by the OS when it is reinstalled,
 *  stable across reboots. Windows: MachineGuid (created once per Windows install).
 *  Linux: /etc/machine-id (generated at install/first boot). macOS: root volume
 *  creation time (a fresh install recreates the system volume). */
async function currentOsId(): Promise<string | null> {
  try {
    if (process.platform === 'win32') {
      const { stdout } = await execFileAsync(
        'reg', ['query', 'HKLM\\SOFTWARE\\Microsoft\\Cryptography', '/v', 'MachineGuid'],
        { timeout: 8_000 },
      )
      const m = stdout.match(/MachineGuid\s+REG_SZ\s+(\S+)/)
      return m ? `win:${m[1]}` : null
    }
    if (process.platform === 'linux') {
      const id = (await readFile('/etc/machine-id', 'utf8')).trim()
      return id ? `linux:${id}` : null
    }
    if (process.platform === 'darwin') {
      const { stdout } = await execFileAsync('stat', ['-f', '%B', '/'], { timeout: 8_000 })
      const t = stdout.trim()
      return t ? `darwin:${t}` : null
    }
  } catch (e) {
    logger.warn(`[os-fingerprint] could not read OS identity: ${e instanceof Error ? e.message : String(e)}`)
  }
  return null
}

async function readStored(): Promise<StoredFingerprint | null> {
  try {
    const parsed = JSON.parse(await readFile(FINGERPRINT_FILE, 'utf8')) as StoredFingerprint
    return typeof parsed?.osId === 'string' && parsed.osId ? parsed : null
  } catch {
    return null
  }
}

/** Compare the stored fingerprint against the live OS identity. Read-only — call
 *  stampOsFingerprint() once the restore plan (if any) has been persisted. */
export async function checkOsFingerprint(): Promise<OsFingerprintStatus> {
  const osId = await currentOsId()
  if (!osId) return 'unknown'
  const stored = await readStored()
  if (!stored) return 'first-stamp'
  return stored.osId === osId ? 'match' : 'changed'
}

/** Persist the current OS identity so future boots compare against it. Best-effort. */
export async function stampOsFingerprint(): Promise<void> {
  const osId = await currentOsId()
  if (!osId) return
  const stamp: StoredFingerprint = { osId, platform: process.platform, recordedAt: new Date().toISOString() }
  try {
    await writeFile(FINGERPRINT_FILE, JSON.stringify(stamp, null, 2))
  } catch (e) {
    logger.warn(`[os-fingerprint] could not write ${FINGERPRINT_FILE}: ${e instanceof Error ? e.message : String(e)}`)
  }
}
