export interface ZimVariant {
  key: string
  label: string
  kiwixName: string
  approxBytes: number
  description: string
}

export interface ZimSource {
  sourceId: string
  label: string
  description: string
  category: string
  faviconUrl?: string
  kiwixDir: string
  variants: ZimVariant[]
  defaultVariant: string
}

export const ZIM_CATEGORIES = [
  'Reference',
  'Education',
  'How-To',
  'Development',
  'Books',
  'Medical',
  'Science',
  'Survival',
  'Entertainment',
  'Kids',
  'Maps',
  'Religion',
]

export const ZIM_CATALOG: ZimSource[] = [
  // ── Reference ────────────────────────────────────────────────────────────
  {
    sourceId: 'wikipedia',
    label: 'Wikipedia',
    description: 'The free encyclopedia — 7M+ English articles',
    category: 'Reference',
    faviconUrl: 'https://en.wikipedia.org/favicon.ico',
    kiwixDir: 'wikipedia',
    defaultVariant: 'mini',
    variants: [
      {
        key: 'mini',
        label: 'Mini (~8 GB)',
        kiwixName: 'wikipedia_en_all_mini',
        approxBytes: 8_000_000_000,
        description: 'All articles with images, no videos',
      },
      {
        key: 'nopic',
        label: 'No-Pic (~4 GB)',
        kiwixName: 'wikipedia_en_all_nopic',
        approxBytes: 4_000_000_000,
        description: 'Text only, no images — smallest download',
      },
      {
        key: 'maxi',
        label: 'Full (~90 GB)',
        kiwixName: 'wikipedia_en_all_maxi',
        approxBytes: 90_000_000_000,
        description: 'Everything including high-res images',
      },
      {
        key: 'simple',
        label: 'Simple English (~500 MB)',
        kiwixName: 'wikipedia_en_simple_all_mini',
        approxBytes: 500_000_000,
        description: 'Simple English Wikipedia — ~450k articles',
      },
    ],
  },
  {
    sourceId: 'wiktionary',
    label: 'Wiktionary',
    description: 'Multilingual dictionary and thesaurus',
    category: 'Reference',
    faviconUrl: 'https://en.wiktionary.org/favicon.ico',
    kiwixDir: 'wiktionary',
    defaultVariant: 'nopic',
    variants: [
      {
        key: 'nopic',
        label: 'English (~5 GB)',
        kiwixName: 'wiktionary_en_all_nopic',
        approxBytes: 5_000_000_000,
        description: 'All English Wiktionary entries (text only)',
      },
    ],
  },
  {
    sourceId: 'wikiquote',
    label: 'Wikiquote',
    description: 'A free collection of notable quotations',
    category: 'Reference',
    faviconUrl: 'https://en.wikiquote.org/favicon.ico',
    kiwixDir: 'wikiquote',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~500 MB)',
        kiwixName: 'wikiquote_en_all_maxi',
        approxBytes: 500_000_000,
        description: 'All English Wikiquote',
      },
    ],
  },
  {
    sourceId: 'wikivoyage',
    label: 'Wikivoyage',
    description: 'Travel guide for destinations and itineraries',
    category: 'Reference',
    faviconUrl: 'https://en.wikivoyage.org/favicon.ico',
    kiwixDir: 'wikivoyage',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~800 MB)',
        kiwixName: 'wikivoyage_en_all_maxi',
        approxBytes: 800_000_000,
        description: 'All English Wikivoyage travel guides',
      },
    ],
  },
  {
    sourceId: 'wikinews',
    label: 'Wikinews',
    description: 'Free-content news source with articles by volunteers',
    category: 'Reference',
    faviconUrl: 'https://en.wikinews.org/favicon.ico',
    kiwixDir: 'wikinews',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~1.5 GB)',
        kiwixName: 'wikinews_en_all_maxi',
        approxBytes: 1_500_000_000,
        description: 'All English Wikinews articles',
      },
    ],
  },
  {
    sourceId: 'factbook',
    label: 'CIA World Factbook',
    description: 'Country profiles and statistics',
    category: 'Reference',
    faviconUrl: 'https://www.cia.gov/the-world-factbook/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~100 MB)',
        kiwixName: 'theworldfactbook_en_all',
        approxBytes: 100_000_000,
        description: 'CIA World Factbook — country data and statistics',
      },
    ],
  },
  {
    sourceId: 'citizendium',
    label: 'Citizendium',
    description: 'Expert-reviewed encyclopedia — a reliable complement to Wikipedia',
    category: 'Reference',
    faviconUrl: 'https://en.citizendium.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~500 MB)',
        kiwixName: 'citizendium.org_en_all_maxi',
        approxBytes: 500_000_000,
        description: 'Expert-authored and reviewed articles',
      },
    ],
  },
  {
    sourceId: 'rationalwiki',
    label: 'RationalWiki',
    description: 'Science-based skepticism, pseudoscience debunking, and critical thinking',
    category: 'Reference',
    faviconUrl: 'https://rationalwiki.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~200 MB)',
        kiwixName: 'rationalwiki_en_all_maxi',
        approxBytes: 200_000_000,
        description: 'RationalWiki articles on science, skepticism, and critical analysis',
      },
    ],
  },
  {
    sourceId: 'hitchwiki',
    label: 'Hitchwiki',
    description: 'Collaborative guide to hitchhiking and low-cost travel worldwide',
    category: 'Reference',
    faviconUrl: 'https://hitchwiki.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~50 MB)',
        kiwixName: 'hitchwiki_en_all_maxi',
        approxBytes: 50_000_000,
        description: 'Hitchhiking tips, routes, and travel guides',
      },
    ],
  },
  {
    sourceId: 'bogleheads',
    label: 'Bogleheads',
    description: 'Personal finance and index-fund investing wiki',
    category: 'Reference',
    faviconUrl: 'https://www.bogleheads.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~100 MB)',
        kiwixName: 'bogleheads_en_all_maxi',
        approxBytes: 100_000_000,
        description: 'Passive investing, personal finance, and retirement planning',
      },
    ],
  },
  {
    sourceId: 'stackexchange_society',
    label: 'Stack Exchange: Society',
    description: 'Q&A on law, money, travel, aviation, philosophy, and history',
    category: 'Reference',
    faviconUrl: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'law',
    variants: [
      {
        key: 'law',
        label: 'Law (~176 MB)',
        kiwixName: 'law.stackexchange.com_en_all',
        approxBytes: 176_000_000,
        description: 'Q&A on legal questions',
      },
      {
        key: 'money',
        label: 'Personal Finance (~300 MB)',
        kiwixName: 'money.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A on personal finance and investing',
      },
      {
        key: 'travel',
        label: 'Travel (~438 MB)',
        kiwixName: 'travel.stackexchange.com_en_all',
        approxBytes: 438_000_000,
        description: 'Q&A on travel and tourism',
      },
      {
        key: 'aviation',
        label: 'Aviation (~480 MB)',
        kiwixName: 'aviation.stackexchange.com_en_all',
        approxBytes: 480_000_000,
        description: 'Q&A on aviation and flight',
      },
      {
        key: 'philosophy',
        label: 'Philosophy (~195 MB)',
        kiwixName: 'philosophy.stackexchange.com_en_all',
        approxBytes: 195_000_000,
        description: 'Q&A on philosophy',
      },
      {
        key: 'history',
        label: 'History (~304 MB)',
        kiwixName: 'history.stackexchange.com_en_all',
        approxBytes: 304_000_000,
        description: 'Q&A on history',
      },
    ],
  },
  // ── Education ─────────────────────────────────────────────────────────────
  {
    sourceId: 'ted',
    label: 'TED Talks',
    description: 'Ideas worth spreading — offline video lectures',
    category: 'Education',
    faviconUrl: 'https://www.ted.com/favicon.ico',
    kiwixDir: 'ted',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'All (~82 GB)',
        kiwixName: 'ted_mul_all',
        approxBytes: 82_000_000_000,
        description: 'All TED Talks (multilingual)',
      },
    ],
  },
  {
    sourceId: 'khanacademy',
    label: 'Khan Academy Lite',
    description: 'Offline learning videos and quizzes',
    category: 'Education',
    faviconUrl: 'https://www.khanacademy.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~45 GB)',
        kiwixName: 'khanacademy_en_all',
        approxBytes: 45_000_000_000,
        description: 'All Khan Academy content',
      },
    ],
  },
  {
    sourceId: 'freecodecamp',
    label: 'freeCodeCamp',
    description: 'Coding curriculum and exercises',
    category: 'Education',
    faviconUrl: 'https://www.freecodecamp.org/favicon.ico',
    kiwixDir: 'freecodecamp',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full curriculum (~10 MB)',
        kiwixName: 'freecodecamp_en_all',
        approxBytes: 10_000_000,
        description: 'All freeCodeCamp curriculum',
      },
      {
        key: 'javascript',
        label: 'JavaScript only (~10 MB)',
        kiwixName: 'freecodecamp_en_javascript-algorithms-and-data-structures',
        approxBytes: 10_000_000,
        description: 'JavaScript algorithms and data structures track',
      },
    ],
  },
  {
    sourceId: 'wikiversity',
    label: 'Wikiversity',
    description: 'Free learning resources and research at all levels',
    category: 'Education',
    faviconUrl: 'https://en.wikiversity.org/favicon.ico',
    kiwixDir: 'wikiversity',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~4 GB)',
        kiwixName: 'wikiversity_en_all_maxi',
        approxBytes: 4_000_000_000,
        description: 'All English Wikiversity resources',
      },
    ],
  },
  // ── How-To ────────────────────────────────────────────────────────────────
  // NOTE: WikiHow was removed — kiwix pulled it from the public mirror over content
  // licensing, so it's no longer downloadable. (Re-add only if it returns to download.kiwix.org.)
  {
    sourceId: 'ifixit',
    label: 'iFixit',
    description: 'Repair guides for electronics and appliances',
    category: 'How-To',
    faviconUrl: 'https://www.ifixit.com/favicon.ico',
    kiwixDir: 'ifixit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~5 GB)',
        kiwixName: 'ifixit_en_all',
        approxBytes: 5_000_000_000,
        description: 'Complete English repair guide library',
      },
    ],
  },
  {
    sourceId: 'appropedia',
    label: 'Appropedia',
    description: 'Sustainability and appropriate-technology how-to guides',
    category: 'How-To',
    faviconUrl: 'https://www.appropedia.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~1.8 GB)',
        kiwixName: 'appropedia_en_all_maxi',
        approxBytes: 1_800_000_000,
        description: 'Full Appropedia content',
      },
    ],
  },
  {
    sourceId: 'energypedia',
    label: 'Energypedia',
    description: 'Renewable energy and sustainable development wiki — 6,000+ articles',
    category: 'How-To',
    faviconUrl: 'https://energypedia.info/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~200 MB)',
        kiwixName: 'energypedia_en_all_maxi',
        approxBytes: 200_000_000,
        description: 'Solar, wind, biogas, and clean-energy how-to articles',
      },
    ],
  },
  {
    sourceId: 'restarters',
    label: 'Restarters Wiki',
    description: 'Repair café and right-to-repair community knowledge base',
    category: 'How-To',
    faviconUrl: 'https://restarters.net/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~30 MB)',
        kiwixName: 'restarters_en_all_maxi',
        approxBytes: 30_000_000,
        description: 'Community repair guides and fault diagnosis tips',
      },
    ],
  },
  {
    sourceId: 'stackexchange_skills',
    label: 'Stack Exchange: Skills & Trades',
    description: 'Q&A on fitness, woodworking, engineering, music, and medical sciences',
    category: 'How-To',
    faviconUrl: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'fitness',
    variants: [
      {
        key: 'fitness',
        label: 'Fitness (~150 MB)',
        kiwixName: 'fitness.stackexchange.com_en_all',
        approxBytes: 150_000_000,
        description: 'Q&A on physical fitness and exercise',
      },
      {
        key: 'woodworking',
        label: 'Woodworking (~80 MB)',
        kiwixName: 'woodworking.stackexchange.com_en_all',
        approxBytes: 80_000_000,
        description: 'Q&A on woodworking and carpentry',
      },
      {
        key: 'engineering',
        label: 'Engineering (~150 MB)',
        kiwixName: 'engineering.stackexchange.com_en_all',
        approxBytes: 150_000_000,
        description: 'Q&A on mechanical and civil engineering',
      },
      {
        key: 'music',
        label: 'Music (~200 MB)',
        kiwixName: 'music.stackexchange.com_en_all',
        approxBytes: 200_000_000,
        description: 'Q&A on music theory and practice',
      },
      {
        key: 'medicalsciences',
        label: 'Medical Sciences (~58 MB)',
        kiwixName: 'medicalsciences.stackexchange.com_en_all',
        approxBytes: 58_000_000,
        description: 'Q&A on medical science for practitioners and students',
      },
    ],
  },
  // ── Development ───────────────────────────────────────────────────────────
  {
    sourceId: 'stackoverflow',
    label: 'Stack Overflow',
    description: 'Q&A for programmers — top voted answers',
    category: 'Development',
    faviconUrl: 'https://stackoverflow.com/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'full',
    variants: [
      {
        key: 'full',
        label: 'Full (~50 GB)',
        kiwixName: 'stackoverflow.com_en_all',
        approxBytes: 50_000_000_000,
        description: 'All questions and answers',
      },
    ],
  },
  {
    sourceId: 'stackexchange',
    label: 'Stack Exchange: Tech',
    description: 'Q&A communities for sysadmin, security, data science, and more',
    category: 'Development',
    faviconUrl: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'superuser',
    variants: [
      {
        key: 'superuser',
        label: 'Super User (~2 GB)',
        kiwixName: 'superuser.com_en_all',
        approxBytes: 2_000_000_000,
        description: 'Q&A for computer enthusiasts and power users',
      },
      {
        key: 'serverfault',
        label: 'Server Fault (~1.5 GB)',
        kiwixName: 'serverfault.com_en_all',
        approxBytes: 1_500_000_000,
        description: 'Q&A for system and network administrators',
      },
      {
        key: 'askubuntu',
        label: 'Ask Ubuntu (~1.8 GB)',
        kiwixName: 'askubuntu.com_en_all',
        approxBytes: 1_800_000_000,
        description: 'Q&A for Ubuntu users and developers',
      },
      {
        key: 'unix',
        label: 'Unix & Linux (~800 MB)',
        kiwixName: 'unix.stackexchange.com_en_all',
        approxBytes: 800_000_000,
        description: 'Q&A for Unix and Linux users',
      },
      {
        key: 'security',
        label: 'Information Security (~600 MB)',
        kiwixName: 'security.stackexchange.com_en_all',
        approxBytes: 600_000_000,
        description: 'Q&A on cybersecurity and infosec',
      },
      {
        key: 'networkengineering',
        label: 'Network Engineering (~150 MB)',
        kiwixName: 'networkengineering.stackexchange.com_en_all',
        approxBytes: 150_000_000,
        description: 'Q&A on network design and administration',
      },
      {
        key: 'datascience',
        label: 'Data Science (~300 MB)',
        kiwixName: 'datascience.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A on data science and machine learning',
      },
      {
        key: 'devops',
        label: 'DevOps (~100 MB)',
        kiwixName: 'devops.stackexchange.com_en_all',
        approxBytes: 100_000_000,
        description: 'Q&A on DevOps practices and tooling',
      },
      {
        key: 'electronics',
        label: 'Electronics (~600 MB)',
        kiwixName: 'electronics.stackexchange.com_en_all',
        approxBytes: 600_000_000,
        description: 'Q&A for electrical engineers',
      },
      {
        key: 'raspberrypi',
        label: 'Raspberry Pi (~200 MB)',
        kiwixName: 'raspberrypi.stackexchange.com_en_all',
        approxBytes: 200_000_000,
        description: 'Q&A for Raspberry Pi users',
      },
      {
        key: 'arduino',
        label: 'Arduino (~200 MB)',
        kiwixName: 'arduino.stackexchange.com_en_all',
        approxBytes: 200_000_000,
        description: 'Q&A for Arduino users',
      },
      {
        key: 'diy',
        label: 'Home Improvement (~500 MB)',
        kiwixName: 'diy.stackexchange.com_en_all',
        approxBytes: 500_000_000,
        description: 'Q&A for home improvement and DIY',
      },
      {
        key: 'cooking',
        label: 'Cooking (~300 MB)',
        kiwixName: 'cooking.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A for professional and amateur chefs',
      },
      {
        key: 'mechanics',
        label: 'Motor Vehicles (~300 MB)',
        kiwixName: 'mechanics.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A for motor vehicle maintenance and repair',
      },
      {
        key: 'outdoors',
        label: 'The Great Outdoors (~100 MB)',
        kiwixName: 'outdoors.stackexchange.com_en_all',
        approxBytes: 100_000_000,
        description: 'Q&A for outdoor activities',
      },
      {
        key: 'gardening',
        label: 'Gardening (~100 MB)',
        kiwixName: 'gardening.stackexchange.com_en_all',
        approxBytes: 100_000_000,
        description: 'Q&A for gardening and landscaping',
      },
      {
        key: 'sustainability',
        label: 'Sustainable Living (~100 MB)',
        kiwixName: 'sustainability.stackexchange.com_en_all',
        approxBytes: 100_000_000,
        description: 'Q&A for sustainable living',
      },
    ],
  },
  {
    sourceId: 'archlinux',
    label: 'Arch Linux Wiki',
    description: 'Linux system administration reference',
    category: 'Development',
    faviconUrl: 'https://archlinux.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~30 MB)',
        kiwixName: 'archlinux_en_all_maxi',
        approxBytes: 30_000_000,
        description: 'Complete Arch Linux Wiki',
      },
    ],
  },
  {
    sourceId: 'alpine_linux',
    label: 'Alpine Linux Wiki',
    description: 'Lightweight Linux distribution documentation and reference',
    category: 'Development',
    faviconUrl: 'https://alpinelinux.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~3 MB)',
        kiwixName: 'alpinelinux_en_all_maxi',
        approxBytes: 3_000_000,
        description: 'Alpine Linux Wiki',
      },
    ],
  },
  {
    sourceId: 'python_docs',
    label: 'DevDocs: Python',
    description: 'Official Python language and standard-library docs',
    category: 'Development',
    faviconUrl: 'https://www.python.org/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~5 MB)',
        kiwixName: 'devdocs_en_python',
        approxBytes: 5_000_000,
        description: 'Python official documentation',
      },
    ],
  },
  {
    sourceId: 'devdocs_javascript',
    label: 'DevDocs: JavaScript',
    description: 'MDN JavaScript documentation — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~50 MB)',
        kiwixName: 'devdocs_en_javascript',
        approxBytes: 50_000_000,
        description: 'MDN JavaScript reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_css',
    label: 'DevDocs: CSS',
    description: 'MDN CSS documentation — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~20 MB)',
        kiwixName: 'devdocs_en_css',
        approxBytes: 20_000_000,
        description: 'MDN CSS reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_typescript',
    label: 'DevDocs: TypeScript',
    description: 'TypeScript language reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~5 MB)',
        kiwixName: 'devdocs_en_typescript',
        approxBytes: 5_000_000,
        description: 'TypeScript language and compiler reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_rust',
    label: 'DevDocs: Rust',
    description: 'Rust language and standard library reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~6 MB)',
        kiwixName: 'devdocs_en_rust',
        approxBytes: 6_000_000,
        description: 'Rust standard library and language docs',
      },
    ],
  },
  {
    sourceId: 'devdocs_go',
    label: 'DevDocs: Go',
    description: 'Go language and standard library reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~4 MB)',
        kiwixName: 'devdocs_en_go',
        approxBytes: 4_000_000,
        description: 'Go standard library and language docs',
      },
    ],
  },
  {
    sourceId: 'devdocs_nodejs',
    label: 'DevDocs: Node.js',
    description: 'Node.js API reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~5 MB)',
        kiwixName: 'devdocs_en_node',
        approxBytes: 5_000_000,
        description: 'Node.js API documentation',
      },
    ],
  },
  {
    sourceId: 'devdocs_php',
    label: 'DevDocs: PHP',
    description: 'PHP language and function reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~8 MB)',
        kiwixName: 'devdocs_en_php',
        approxBytes: 8_000_000,
        description: 'PHP language and function reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_ruby',
    label: 'DevDocs: Ruby',
    description: 'Ruby language and standard library reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~3 MB)',
        kiwixName: 'devdocs_en_ruby',
        approxBytes: 3_000_000,
        description: 'Ruby core and standard library docs',
      },
    ],
  },
  {
    sourceId: 'devdocs_react',
    label: 'DevDocs: React',
    description: 'React framework reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~3 MB)',
        kiwixName: 'devdocs_en_react',
        approxBytes: 3_000_000,
        description: 'React API and hooks reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_vue',
    label: 'DevDocs: Vue',
    description: 'Vue.js framework reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~2 MB)',
        kiwixName: 'devdocs_en_vue',
        approxBytes: 2_000_000,
        description: 'Vue.js API and guide reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_tailwindcss',
    label: 'DevDocs: Tailwind CSS',
    description: 'Tailwind CSS utility class reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~2 MB)',
        kiwixName: 'devdocs_en_tailwindcss',
        approxBytes: 2_000_000,
        description: 'Tailwind CSS utility class reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_docker',
    label: 'DevDocs: Docker',
    description: 'Docker CLI and API reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~5 MB)',
        kiwixName: 'devdocs_en_docker',
        approxBytes: 5_000_000,
        description: 'Docker CLI, Compose, and API reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_postgresql',
    label: 'DevDocs: PostgreSQL',
    description: 'PostgreSQL reference manual — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~10 MB)',
        kiwixName: 'devdocs_en_postgresql',
        approxBytes: 10_000_000,
        description: 'PostgreSQL SQL and administration reference',
      },
    ],
  },
  {
    sourceId: 'devdocs_bash',
    label: 'DevDocs: Bash',
    description: 'Bash shell reference — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~2 MB)',
        kiwixName: 'devdocs_en_bash',
        approxBytes: 2_000_000,
        description: 'GNU Bash reference manual',
      },
    ],
  },
  {
    sourceId: 'devdocs_git',
    label: 'DevDocs: Git',
    description: 'Git reference manual — offline',
    category: 'Development',
    faviconUrl: 'https://devdocs.io/favicon.ico',
    kiwixDir: 'devdocs',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~2 MB)',
        kiwixName: 'devdocs_en_git',
        approxBytes: 2_000_000,
        description: 'Git commands and concepts reference',
      },
    ],
  },
  {
    sourceId: 'cloudflare_learning',
    label: 'Cloudflare Learning Center',
    description: 'Networking, security, and web performance reference — DNS, TLS, DDoS, CDN explained',
    category: 'Development',
    faviconUrl: 'https://cloudflare.com/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~182 MB)',
        kiwixName: 'cloudflare.com_en_learning-center',
        approxBytes: 182_000_000,
        description: 'Networking and security concepts reference',
      },
    ],
  },
  // ── Books ─────────────────────────────────────────────────────────────────
  {
    sourceId: 'gutenberg',
    label: 'Project Gutenberg',
    description: '70,000+ free public domain ebooks',
    category: 'Books',
    faviconUrl: 'https://www.gutenberg.org/favicon.ico',
    kiwixDir: 'gutenberg',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~60 GB)',
        kiwixName: 'gutenberg_en_all',
        approxBytes: 60_000_000_000,
        description: 'All English books',
      },
    ],
  },
  {
    sourceId: 'wikibooks',
    label: 'Wikibooks',
    description: 'Open-content textbooks and how-to manuals',
    category: 'Books',
    faviconUrl: 'https://en.wikibooks.org/favicon.ico',
    kiwixDir: 'wikibooks',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~600 MB)',
        kiwixName: 'wikibooks_en_all_maxi',
        approxBytes: 600_000_000,
        description: 'All English Wikibooks',
      },
    ],
  },
  {
    sourceId: 'wikisource',
    label: 'Wikisource',
    description: 'Public-domain books and primary-source texts',
    category: 'Books',
    faviconUrl: 'https://en.wikisource.org/favicon.ico',
    kiwixDir: 'wikisource',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~2.5 GB)',
        kiwixName: 'wikisource_en_all_maxi',
        approxBytes: 2_500_000_000,
        description: 'All English Wikisource texts',
      },
    ],
  },
  // ── Medical ───────────────────────────────────────────────────────────────
  {
    sourceId: 'wikimed',
    label: 'WikiMed Medical',
    description: "Wikipedia's curated medical content",
    category: 'Medical',
    faviconUrl: 'https://en.wikipedia.org/favicon.ico',
    kiwixDir: 'wikipedia',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~1 GB)',
        kiwixName: 'wikipedia_en_medicine_maxi',
        approxBytes: 1_000_000_000,
        description: 'Medical Wikipedia with images',
      },
    ],
  },
  {
    sourceId: 'mdwiki',
    label: 'MDWiki Medical Encyclopedia',
    description: 'Medical reference derived from Wiki Project Med',
    category: 'Medical',
    faviconUrl: 'https://en.wikipedia.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full with images (~2 GB)',
        kiwixName: 'mdwiki_en_all_maxi',
        approxBytes: 2_000_000_000,
        description: 'Medical encyclopedia with images',
      },
    ],
  },
  {
    sourceId: 'wikem',
    label: 'WikEM',
    description: 'Emergency medicine reference',
    category: 'Medical',
    faviconUrl: 'https://wikem.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'nopic',
    variants: [
      {
        key: 'maxi',
        label: 'Full with images (~150 MB)',
        kiwixName: 'wikem_en_all_maxi',
        approxBytes: 150_000_000,
        description: 'Emergency medicine reference with images',
      },
      {
        key: 'nopic',
        label: 'No images (~20 MB)',
        kiwixName: 'wikem_en_all_nopic',
        approxBytes: 20_000_000,
        description: 'Emergency medicine reference, text only',
      },
    ],
  },
  {
    sourceId: 'librepathology',
    label: 'Libre Pathology',
    description: 'Open pathology reference — histology, cytology, and surgical pathology',
    category: 'Medical',
    faviconUrl: 'https://librepathology.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~700 MB)',
        kiwixName: 'librepathology_en_all_maxi',
        approxBytes: 700_000_000,
        description: 'Pathology reference with microscopy images',
      },
    ],
  },
  {
    sourceId: 'skin_of_color',
    label: 'Skin of Color Society',
    description: 'Dermatology reference focused on skin of color',
    category: 'Medical',
    faviconUrl: 'https://skinofcolorsociety.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~50 MB)',
        kiwixName: 'skin-of-color-society_en_all',
        approxBytes: 50_000_000,
        description: 'Dermatology conditions and treatments across skin tones',
      },
    ],
  },
  {
    sourceId: 'usda_nutrition',
    label: 'USDA Nutritional Database',
    description: 'USDA nutritional data for thousands of foods',
    category: 'Medical',
    faviconUrl: 'https://www.usda.gov/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~5 MB)',
        kiwixName: 'usda-2015_en',
        approxBytes: 5_000_000,
        description: 'USDA nutritional composition data',
      },
    ],
  },
  {
    sourceId: 'libretexts_med',
    label: 'LibreTexts Medicine',
    description: 'Open college-level medical and health science textbooks',
    category: 'Medical',
    faviconUrl: 'https://libretexts.org/favicon.ico',
    kiwixDir: 'libretexts',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~1 GB)',
        kiwixName: 'libretexts.org_en_med',
        approxBytes: 1_000_000_000,
        description: 'College-level medical and health science textbooks',
      },
    ],
  },
  {
    sourceId: 'medlineplus',
    label: 'MedlinePlus',
    description: 'NIH health information — conditions, drugs, and wellness topics',
    category: 'Medical',
    faviconUrl: 'https://medlineplus.gov/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~1.8 GB)',
        kiwixName: 'medlineplus.gov_en_all',
        approxBytes: 1_800_000_000,
        description: 'NIH MedlinePlus health encyclopedia',
      },
    ],
  },
  {
    sourceId: 'nhs_medicines',
    label: 'NHS Medicines Reference',
    description: 'UK National Health Service medicines guide — dosing, side effects, interactions',
    category: 'Medical',
    faviconUrl: 'https://www.nhs.uk/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~16 MB)',
        kiwixName: 'nhs.uk_en_medicines',
        approxBytes: 16_000_000,
        description: 'NHS medicines guide',
      },
    ],
  },
  {
    sourceId: 'fas_military_medicine',
    label: 'Military Field Medicine',
    description: 'US military field medical guides — trauma care, triage, and combat medicine',
    category: 'Medical',
    faviconUrl: 'https://fas.org/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~78 MB)',
        kiwixName: 'fas-military-medicine_en',
        approxBytes: 78_000_000,
        description: 'Military field medicine and trauma care',
      },
    ],
  },
  // ── Science ───────────────────────────────────────────────────────────────
  {
    sourceId: 'phet',
    label: 'PhET Simulations',
    description: 'Interactive science and math simulations from University of Colorado',
    category: 'Science',
    faviconUrl: 'https://phet.colorado.edu/favicon.ico',
    kiwixDir: 'phet',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~100 MB)',
        kiwixName: 'phet_en_all',
        approxBytes: 100_000_000,
        description: 'All PhET interactive simulations',
      },
    ],
  },
  {
    sourceId: 'libretexts',
    label: 'LibreTexts',
    description: 'Open college-level textbooks across math, science, and engineering',
    category: 'Science',
    faviconUrl: 'https://libretexts.org/favicon.ico',
    kiwixDir: 'libretexts',
    defaultVariant: 'math',
    variants: [
      {
        key: 'math',
        label: 'Mathematics (~792 MB)',
        kiwixName: 'libretexts.org_en_math',
        approxBytes: 792_000_000,
        description: 'College-level mathematics textbooks',
      },
      {
        key: 'phys',
        label: 'Physics (~534 MB)',
        kiwixName: 'libretexts.org_en_phys',
        approxBytes: 534_000_000,
        description: 'College-level physics textbooks',
      },
      {
        key: 'chem',
        label: 'Chemistry (~2 GB)',
        kiwixName: 'libretexts.org_en_chem',
        approxBytes: 2_000_000_000,
        description: 'College-level chemistry textbooks',
      },
      {
        key: 'bio',
        label: 'Biology (~2.1 GB)',
        kiwixName: 'libretexts.org_en_bio',
        approxBytes: 2_100_000_000,
        description: 'College-level biology textbooks',
      },
      {
        key: 'eng',
        label: 'Engineering (~647 MB)',
        kiwixName: 'libretexts.org_en_eng',
        approxBytes: 647_000_000,
        description: 'College-level engineering textbooks',
      },
      {
        key: 'stats',
        label: 'Statistics (~206 MB)',
        kiwixName: 'libretexts.org_en_stats',
        approxBytes: 206_000_000,
        description: 'College-level statistics textbooks',
      },
    ],
  },
  {
    sourceId: 'internet_encyclopedia_philosophy',
    label: 'Internet Encyclopedia of Philosophy',
    description: 'Peer-reviewed philosophy reference — 900+ scholarly articles',
    category: 'Science',
    faviconUrl: 'https://iep.utm.edu/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~120 MB)',
        kiwixName: 'internet-encyclopedia-philosophy_en_all',
        approxBytes: 120_000_000,
        description: 'Scholarly philosophy reference',
      },
    ],
  },
  {
    sourceId: 'proofwiki',
    label: 'ProofWiki',
    description: 'Compendium of mathematical proofs',
    category: 'Science',
    faviconUrl: 'https://proofwiki.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~100 MB)',
        kiwixName: 'proofwiki_en_all_maxi',
        approxBytes: 100_000_000,
        description: 'All mathematical proofs',
      },
    ],
  },
  {
    sourceId: 'wikispecies',
    label: 'Wikispecies',
    description: 'Free taxonomy directory of all known species',
    category: 'Science',
    faviconUrl: 'https://species.wikimedia.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Full (~3.2 GB)',
        kiwixName: 'wikispecies_en_all_maxi',
        approxBytes: 3_200_000_000,
        description: 'Complete species taxonomy with images',
      },
      {
        key: 'nopic',
        label: 'No images (~800 MB)',
        kiwixName: 'wikispecies_en_all_nopic',
        approxBytes: 800_000_000,
        description: 'Complete species taxonomy, text only',
      },
    ],
  },
  {
    sourceId: 'artofproblemsolving',
    label: 'Art of Problem Solving',
    description: 'Competitive mathematics wiki — olympiad problems, proofs, and techniques',
    category: 'Science',
    faviconUrl: 'https://artofproblemsolving.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~50 MB)',
        kiwixName: 'artofproblemsolving_en_all_maxi',
        approxBytes: 50_000_000,
        description: 'Competitive math wiki and problem archive',
      },
    ],
  },
  {
    sourceId: 'stackexchange_science',
    label: 'Stack Exchange: Science',
    description: 'Q&A on math, physics, biology, chemistry, statistics, and space',
    category: 'Science',
    faviconUrl: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'math',
    variants: [
      {
        key: 'math',
        label: 'Mathematics (~6.9 GB)',
        kiwixName: 'math.stackexchange.com_en_all',
        approxBytes: 6_900_000_000,
        description: 'Q&A on mathematics at all levels',
      },
      {
        key: 'stats',
        label: 'Cross Validated / Statistics (~1.5 GB)',
        kiwixName: 'stats.stackexchange.com_en_all',
        approxBytes: 1_500_000_000,
        description: 'Q&A on statistics, ML, and data analysis',
      },
      {
        key: 'physics',
        label: 'Physics (~1.7 GB)',
        kiwixName: 'physics.stackexchange.com_en_all',
        approxBytes: 1_700_000_000,
        description: 'Q&A on physics',
      },
      {
        key: 'biology',
        label: 'Biology (~400 MB)',
        kiwixName: 'biology.stackexchange.com_en_all',
        approxBytes: 400_000_000,
        description: 'Q&A on biology',
      },
      {
        key: 'chemistry',
        label: 'Chemistry (~300 MB)',
        kiwixName: 'chemistry.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A on chemistry',
      },
      {
        key: 'space',
        label: 'Space Exploration (~300 MB)',
        kiwixName: 'space.stackexchange.com_en_all',
        approxBytes: 300_000_000,
        description: 'Q&A on space exploration and astronautics',
      },
      {
        key: 'astronomy',
        label: 'Astronomy (~200 MB)',
        kiwixName: 'astronomy.stackexchange.com_en_all',
        approxBytes: 200_000_000,
        description: 'Q&A on astronomy and astrophysics',
      },
      {
        key: 'earthscience',
        label: 'Earth Science (~100 MB)',
        kiwixName: 'earthscience.stackexchange.com_en_all',
        approxBytes: 100_000_000,
        description: 'Q&A on geology, meteorology, and oceanography',
      },
    ],
  },
  // ── Survival ─────────────────────────────────────────────────────────────
  {
    sourceId: 'zimgit_post_disaster',
    label: 'Post-Disaster Guide',
    description: 'Community recovery guide for natural disasters and emergencies',
    category: 'Survival',
    faviconUrl: 'https://github.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~600 MB)',
        kiwixName: 'zimgit-post-disaster_en',
        approxBytes: 600_000_000,
        description: 'Community recovery guide',
      },
    ],
  },
  {
    sourceId: 'zimgit_food',
    label: 'Food Preparation Guide',
    description: 'Offline food preservation, preparation, and cooking skills',
    category: 'Survival',
    faviconUrl: 'https://github.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~90 MB)',
        kiwixName: 'zimgit-food-preparation_en',
        approxBytes: 90_000_000,
        description: 'Food preparation and preservation',
      },
    ],
  },
  {
    sourceId: 'zimgit_knots',
    label: 'Knot-Tying Reference',
    description: 'Illustrated knot-tying guide for outdoor and emergency use',
    category: 'Survival',
    faviconUrl: 'https://github.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~30 MB)',
        kiwixName: 'zimgit-knots_en',
        approxBytes: 30_000_000,
        description: 'Illustrated knot-tying reference',
      },
    ],
  },
  {
    sourceId: 'zimgit_medicine',
    label: 'Survival Medicine Reference',
    description: 'Field medicine and first-aid reference for austere environments',
    category: 'Survival',
    faviconUrl: 'https://github.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~70 MB)',
        kiwixName: 'zimgit-medicine_en',
        approxBytes: 70_000_000,
        description: 'Field medicine and first-aid',
      },
    ],
  },
  {
    sourceId: 'zimgit_water',
    label: 'Water Treatment Guide',
    description: 'Water sourcing, filtration, and purification methods offline',
    category: 'Survival',
    faviconUrl: 'https://github.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~20 MB)',
        kiwixName: 'zimgit-water_en',
        approxBytes: 20_000_000,
        description: 'Water treatment and purification',
      },
    ],
  },
  {
    sourceId: 'ready_gov',
    label: 'Ready.gov',
    description: 'FEMA official emergency preparedness — disasters, kits, and evacuation plans',
    category: 'Survival',
    faviconUrl: 'https://www.ready.gov/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~2.3 GB)',
        kiwixName: 'www.ready.gov_en',
        approxBytes: 2_300_000_000,
        description: 'FEMA emergency preparedness guides',
      },
    ],
  },
  {
    sourceId: 'survivor_library',
    label: 'Survivor Library',
    description: 'Massive archive of pre-industrial skills, crafts, and self-sufficiency texts',
    category: 'Survival',
    faviconUrl: 'https://survivorlibrary.com/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~235 GB)',
        kiwixName: 'survivorlibrary.com_en_all',
        approxBytes: 235_000_000_000,
        description: 'Complete archive of survival and pre-industrial knowledge',
      },
    ],
  },
  {
    sourceId: 'canadian_prepper',
    label: 'Canadian Prepper',
    description: 'Survival and preparedness video series by Canadian Prepper',
    category: 'Survival',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    kiwixDir: 'videos',
    defaultVariant: 'bugout',
    variants: [
      {
        key: 'bugout',
        label: 'Bug-Out Concepts (~2.7 GB)',
        kiwixName: 'canadian-prepper_en_bugoutconcepts',
        approxBytes: 2_700_000_000,
        description: 'Bug-out planning and evacuation concepts',
      },
      {
        key: 'food',
        label: 'Prepping Food (~2 GB)',
        kiwixName: 'canadian-prepper_en_preppingfood',
        approxBytes: 2_000_000_000,
        description: 'Food storage and preparation for survival',
      },
      {
        key: 'winter',
        label: 'Winter Prepping (~1.2 GB)',
        kiwixName: 'canadian-prepper_en_winterprepping',
        approxBytes: 1_200_000_000,
        description: 'Cold-weather survival and preparation',
      },
    ],
  },
  {
    sourceId: 'urban_prepper',
    label: 'Urban Prepper',
    description: 'Urban and suburban survival preparedness video series',
    category: 'Survival',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    kiwixDir: 'videos',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'All videos (~2.1 GB)',
        kiwixName: 'urban-prepper_en_all',
        approxBytes: 2_100_000_000,
        description: 'Urban survival and preparedness videos',
      },
    ],
  },
  {
    sourceId: '100r',
    label: '100 Rabbits',
    description: 'Off-grid computing, tools, and sailing life — minimal tech that works without infrastructure',
    category: 'Survival',
    faviconUrl: 'https://100r.co/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~160 MB)',
        kiwixName: '100r.co_en_all',
        approxBytes: 160_000_000,
        description: 'Off-grid tools, software, and living guides',
      },
    ],
  },
  {
    sourceId: 'solar_lowtechmagazine',
    label: 'Low-Tech Magazine',
    description: 'Sustainable low-technology solutions — solar-powered site with offline survival relevance',
    category: 'Survival',
    faviconUrl: 'https://solar.lowtechmagazine.com/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~668 MB)',
        kiwixName: 'solar.lowtechmagazine.com_mul_all',
        approxBytes: 668_000_000,
        description: 'Low-tech sustainable solutions and history',
      },
    ],
  },
  {
    sourceId: 'cd3wd',
    label: 'CD3WD',
    description: 'Practical knowledge for developing communities — agriculture, water, construction, health',
    category: 'Survival',
    faviconUrl: 'https://cd3wdproject.org/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~554 MB)',
        kiwixName: 'cd3wdproject.org_en_all',
        approxBytes: 554_000_000,
        description: 'Practical development and survival knowledge',
      },
    ],
  },
  {
    sourceId: 'based_cooking',
    label: 'Based Cooking',
    description: 'Simple, ingredient-focused cooking recipes — no ads, no fluff',
    category: 'Survival',
    faviconUrl: 'https://based.cooking/favicon.ico',
    kiwixDir: 'zimit',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~15 MB)',
        kiwixName: 'based.cooking_en_all',
        approxBytes: 15_000_000,
        description: 'Clean recipe reference',
      },
    ],
  },
  {
    sourceId: 'trueprepper',
    label: 'TruePrepper',
    description: 'Comprehensive emergency preparedness and self-reliance guides',
    category: 'Survival',
    faviconUrl: 'https://trueprepper.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'Full (~1.3 GB)',
        kiwixName: 'trueprepper.com_en_all',
        approxBytes: 1_300_000_000,
        description: 'Emergency preparedness guides',
      },
    ],
  },
  // ── Entertainment ─────────────────────────────────────────────────────────
  {
    sourceId: 'crash_course',
    label: 'Crash Course',
    description: 'Fast-paced educational video series: history, science, literature, and more',
    category: 'Entertainment',
    faviconUrl: 'https://www.youtube.com/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'All Series (~21 GB)',
        kiwixName: 'crashcourse_en_all',
        approxBytes: 21_000_000_000,
        description: 'All Crash Course video series',
      },
    ],
  },
  // ── Kids ──────────────────────────────────────────────────────────────────
  {
    sourceId: 'vikidia',
    label: 'Vikidia',
    description: "Children's encyclopedia — simple, illustrated articles for ages 8–13",
    category: 'Kids',
    faviconUrl: 'https://en.vikidia.org/favicon.ico',
    kiwixDir: 'vikidia',
    defaultVariant: 'en',
    variants: [
      {
        key: 'en',
        label: 'English (~70 MB)',
        kiwixName: 'vikidia_en_all_maxi',
        approxBytes: 70_000_000,
        description: 'English Vikidia',
      },
      {
        key: 'fr',
        label: 'Français (~1.3 GB)',
        kiwixName: 'vikidia_fr_all_maxi',
        approxBytes: 1_300_000_000,
        description: 'French Vikidia',
      },
      {
        key: 'es',
        label: 'Español (~90 MB)',
        kiwixName: 'vikidia_es_all_maxi',
        approxBytes: 90_000_000,
        description: 'Spanish Vikidia',
      },
    ],
  },
  {
    sourceId: 'klexikon',
    label: 'Klexikon',
    description: "German children's encyclopedia for ages 6–12",
    category: 'Kids',
    faviconUrl: 'https://klexikon.zum.de/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'maxi',
    variants: [
      {
        key: 'maxi',
        label: 'Deutsch (~150 MB)',
        kiwixName: 'klexikon_de_all_maxi',
        approxBytes: 150_000_000,
        description: 'German Klexikon with images',
      },
      {
        key: 'nopic',
        label: 'Deutsch, kein Bild (~50 MB)',
        kiwixName: 'klexikon_de_all_nopic',
        approxBytes: 50_000_000,
        description: 'German Klexikon, text only',
      },
    ],
  },
  {
    sourceId: 'african_storybook',
    label: 'African Storybook',
    description: '8,000+ picture books in 30+ African languages — CC BY 4.0',
    category: 'Kids',
    faviconUrl: 'https://www.africanstorybook.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'mul',
    variants: [
      {
        key: 'mul',
        label: 'All Languages (~8.1 GB)',
        kiwixName: 'africanstorybook.org_mul_all',
        approxBytes: 8_100_000_000,
        description: 'Picture books in 30+ African languages',
      },
    ],
  },
  // ── Religion ──────────────────────────────────────────────────────────────
  {
    sourceId: 'chabadpedia',
    label: 'Chabadpedia',
    description: 'Hebrew Chabad encyclopedia of Jewish law, philosophy, and history',
    category: 'Religion',
    faviconUrl: 'https://www.chabad.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'he',
    variants: [
      {
        key: 'he',
        label: 'עברית (~110 MB)',
        kiwixName: 'chabadpedia_he_all_maxi',
        approxBytes: 110_000_000,
        description: 'Chabad encyclopedia in Hebrew',
      },
    ],
  },
  {
    sourceId: 'chabadtext',
    label: 'Chabad Texts',
    description: 'Classical Hebrew religious texts from the Chabad library',
    category: 'Religion',
    faviconUrl: 'https://www.chabad.org/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'he',
    variants: [
      {
        key: 'he',
        label: 'עברית (~16 MB)',
        kiwixName: 'chabadtext_he_all_maxi',
        approxBytes: 16_000_000,
        description: 'Classical Chabad texts in Hebrew',
      },
    ],
  },
  {
    sourceId: 'yeshiva',
    label: 'Yeshiva',
    description: 'Hebrew Jewish learning resource — Torah, halacha, and responsa',
    category: 'Religion',
    faviconUrl: 'https://www.yeshiva.co.il/favicon.ico',
    kiwixDir: 'other',
    defaultVariant: 'he',
    variants: [
      {
        key: 'he',
        label: 'עברית (~50 MB)',
        kiwixName: 'yeshiva_he_all_maxi',
        approxBytes: 50_000_000,
        description: 'Jewish learning content in Hebrew',
      },
    ],
  },
  {
    sourceId: 'stackexchange_faith',
    label: 'Stack Exchange: Faith & Religion',
    description: 'Q&A communities for Islam, Christianity, Buddhism, Hinduism, and Judaism',
    category: 'Religion',
    faviconUrl: 'https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico',
    kiwixDir: 'stack_exchange',
    defaultVariant: 'islam',
    variants: [
      {
        key: 'islam',
        label: 'Islam (~85 MB)',
        kiwixName: 'islam.stackexchange.com_en_all',
        approxBytes: 85_000_000,
        description: 'Q&A on Islamic theology and practice',
      },
      {
        key: 'christianity',
        label: 'Christianity (~150 MB)',
        kiwixName: 'christianity.stackexchange.com_en_all',
        approxBytes: 150_000_000,
        description: 'Q&A on Christian theology and practice',
      },
      {
        key: 'judaism',
        label: 'Judaism (~120 MB)',
        kiwixName: 'judaism.stackexchange.com_en_all',
        approxBytes: 120_000_000,
        description: 'Q&A on Jewish law, philosophy, and practice',
      },
      {
        key: 'buddhism',
        label: 'Buddhism (~80 MB)',
        kiwixName: 'buddhism.stackexchange.com_en_all',
        approxBytes: 80_000_000,
        description: 'Q&A on Buddhist teachings and practice',
      },
      {
        key: 'hinduism',
        label: 'Hinduism (~80 MB)',
        kiwixName: 'hinduism.stackexchange.com_en_all',
        approxBytes: 80_000_000,
        description: 'Q&A on Hindu philosophy and practice',
      },
    ],
  },
]
