// Time / Clock app — per-user world-clock locations, alarms, and timer presets.
//
// Pure metadata CRUD. The actual ringing (sound + companion announcement + the
// snooze/dismiss dialog) and the running-timer/stopwatch countdowns all live on
// the client (see frontend/src/context/TimeAlarmContext.tsx); this route only
// persists the saved definitions. Custom tones are stored elsewhere (a built-in
// synth key, or a music_tracks row generated by the offline music engine) and
// referenced here by the `tone` string.

import { Hono } from 'hono'
import { db } from '@/db'
import { clockLocations, clockAlarms, clockTimers, clockTimerRuns } from '@/db/schema'
import { eq, and, asc } from 'drizzle-orm'
import { requireAuth } from '@/middleware/auth'
import type { AppEnv } from '@/types'

export const time = new Hono<AppEnv>()
time.use('*', requireAuth)

// ── helpers ─────────────────────────────────────────────────────────────────
function str(v: unknown, max: number): string | null {
  if (typeof v !== 'string') return null
  const s = v.trim()
  return s ? s.slice(0, max) : null
}
function int(v: unknown, min: number, max: number): number | null {
  const n = typeof v === 'number' ? v : typeof v === 'string' ? Number(v) : NaN
  if (!Number.isFinite(n)) return null
  const r = Math.round(n)
  return r < min ? min : r > max ? max : r
}
function bool(v: unknown, fallback: boolean): boolean {
  return typeof v === 'boolean' ? v : fallback
}
/** Normalise a repeat-days array to a sorted unique list of weekday ints 0–6. */
function repeatDays(v: unknown): number[] {
  if (!Array.isArray(v)) return []
  const set = new Set<number>()
  for (const d of v) {
    const n = int(d, 0, 6)
    if (n !== null) set.add(n)
  }
  return [...set].sort((a, b) => a - b)
}

// ─── World-clock locations ──────────────────────────────────────────────────
time.get('/locations', async (c) => {
  const user = c.get('user')
  const rows = await db.select().from(clockLocations)
    .where(eq(clockLocations.userId, user.id))
    .orderBy(asc(clockLocations.sortOrder), asc(clockLocations.createdAt))
  return c.json({ locations: rows })
})

time.post('/locations', async (c) => {
  const user = c.get('user')
  const body = await c.req.json().catch(() => ({}))
  const label = str(body.label, 80)
  const timezone = str(body.timezone, 80)
  if (!label || !timezone) return c.json({ error: 'label and timezone required' }, 400)

  const now = new Date()
  const id = crypto.randomUUID()
  await db.insert(clockLocations).values({
    id, userId: user.id, label, timezone,
    sortOrder: int(body.sortOrder, 0, 9999) ?? 0,
    createdAt: now, updatedAt: now,
  })
  const [row] = await db.select().from(clockLocations).where(eq(clockLocations.id, id))
  return c.json({ location: row })
})

time.patch('/locations/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  const [existing] = await db.select().from(clockLocations)
    .where(and(eq(clockLocations.id, id), eq(clockLocations.userId, user.id)))
  if (!existing) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json().catch(() => ({}))
  const patch: Partial<typeof clockLocations.$inferInsert> = { updatedAt: new Date() }
  const label = str(body.label, 80); if (label) patch.label = label
  const tz = str(body.timezone, 80); if (tz) patch.timezone = tz
  const so = int(body.sortOrder, 0, 9999); if (so !== null) patch.sortOrder = so

  await db.update(clockLocations).set(patch).where(eq(clockLocations.id, id))
  const [row] = await db.select().from(clockLocations).where(eq(clockLocations.id, id))
  return c.json({ location: row })
})

time.delete('/locations/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  await db.delete(clockLocations).where(and(eq(clockLocations.id, id), eq(clockLocations.userId, user.id)))
  return c.json({ ok: true })
})

// ─── Alarms ─────────────────────────────────────────────────────────────────
time.get('/alarms', async (c) => {
  const user = c.get('user')
  const rows = await db.select().from(clockAlarms)
    .where(eq(clockAlarms.userId, user.id))
    .orderBy(asc(clockAlarms.hour), asc(clockAlarms.minute))
  return c.json({ alarms: rows.map((a) => ({ ...a, repeatDays: JSON.parse(a.repeatDays) as number[] })) })
})

time.post('/alarms', async (c) => {
  const user = c.get('user')
  const body = await c.req.json().catch(() => ({}))
  const hour = int(body.hour, 0, 23)
  const minute = int(body.minute, 0, 59)
  if (hour === null || minute === null) return c.json({ error: 'hour and minute required' }, 400)

  const now = new Date()
  const id = crypto.randomUUID()
  await db.insert(clockAlarms).values({
    id, userId: user.id,
    label: str(body.label, 80) ?? 'Alarm',
    hour, minute,
    repeatDays: JSON.stringify(repeatDays(body.repeatDays)),
    enabled: bool(body.enabled, true),
    tone: str(body.tone, 200) ?? 'builtin:radar',
    toneName: str(body.toneName, 120),
    announce: bool(body.announce, true),
    snoozeMinutes: int(body.snoozeMinutes, 1, 60) ?? 9,
    createdAt: now, updatedAt: now,
  })
  const [row] = await db.select().from(clockAlarms).where(eq(clockAlarms.id, id))
  return c.json({ alarm: { ...row, repeatDays: JSON.parse(row!.repeatDays) as number[] } })
})

time.patch('/alarms/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  const [existing] = await db.select().from(clockAlarms)
    .where(and(eq(clockAlarms.id, id), eq(clockAlarms.userId, user.id)))
  if (!existing) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json().catch(() => ({}))
  const patch: Partial<typeof clockAlarms.$inferInsert> = { updatedAt: new Date() }
  const label = str(body.label, 80); if (label) patch.label = label
  const hour = int(body.hour, 0, 23); if (hour !== null) patch.hour = hour
  const minute = int(body.minute, 0, 59); if (minute !== null) patch.minute = minute
  if (Array.isArray(body.repeatDays)) patch.repeatDays = JSON.stringify(repeatDays(body.repeatDays))
  if (typeof body.enabled === 'boolean') patch.enabled = body.enabled
  const tone = str(body.tone, 200); if (tone) patch.tone = tone
  if ('toneName' in body) patch.toneName = str(body.toneName, 120)
  if (typeof body.announce === 'boolean') patch.announce = body.announce
  const snooze = int(body.snoozeMinutes, 1, 60); if (snooze !== null) patch.snoozeMinutes = snooze

  await db.update(clockAlarms).set(patch).where(eq(clockAlarms.id, id))
  const [row] = await db.select().from(clockAlarms).where(eq(clockAlarms.id, id))
  return c.json({ alarm: { ...row, repeatDays: JSON.parse(row!.repeatDays) as number[] } })
})

time.delete('/alarms/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  await db.delete(clockAlarms).where(and(eq(clockAlarms.id, id), eq(clockAlarms.userId, user.id)))
  return c.json({ ok: true })
})

// ─── Timer presets ──────────────────────────────────────────────────────────
time.get('/timers', async (c) => {
  const user = c.get('user')
  const rows = await db.select().from(clockTimers)
    .where(eq(clockTimers.userId, user.id))
    .orderBy(asc(clockTimers.sortOrder), asc(clockTimers.createdAt))
  return c.json({ timers: rows })
})

time.post('/timers', async (c) => {
  const user = c.get('user')
  const body = await c.req.json().catch(() => ({}))
  const durationSec = int(body.durationSec, 1, 24 * 3600)
  if (durationSec === null) return c.json({ error: 'durationSec required' }, 400)

  const now = new Date()
  const id = crypto.randomUUID()
  await db.insert(clockTimers).values({
    id, userId: user.id,
    label: str(body.label, 80) ?? 'Timer',
    durationSec,
    tone: str(body.tone, 200) ?? 'builtin:beacon',
    toneName: str(body.toneName, 120),
    announce: bool(body.announce, true),
    sortOrder: int(body.sortOrder, 0, 9999) ?? 0,
    createdAt: now, updatedAt: now,
  })
  const [row] = await db.select().from(clockTimers).where(eq(clockTimers.id, id))
  return c.json({ timer: row })
})

time.patch('/timers/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  const [existing] = await db.select().from(clockTimers)
    .where(and(eq(clockTimers.id, id), eq(clockTimers.userId, user.id)))
  if (!existing) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json().catch(() => ({}))
  const patch: Partial<typeof clockTimers.$inferInsert> = { updatedAt: new Date() }
  const label = str(body.label, 80); if (label) patch.label = label
  const dur = int(body.durationSec, 1, 24 * 3600); if (dur !== null) patch.durationSec = dur
  const tone = str(body.tone, 200); if (tone) patch.tone = tone
  if ('toneName' in body) patch.toneName = str(body.toneName, 120)
  if (typeof body.announce === 'boolean') patch.announce = body.announce
  const so = int(body.sortOrder, 0, 9999); if (so !== null) patch.sortOrder = so

  await db.update(clockTimers).set(patch).where(eq(clockTimers.id, id))
  const [row] = await db.select().from(clockTimers).where(eq(clockTimers.id, id))
  return c.json({ timer: row })
})

time.delete('/timers/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  await db.delete(clockTimers).where(and(eq(clockTimers.id, id), eq(clockTimers.userId, user.id)))
  return c.json({ ok: true })
})

// ─── Running timer countdowns (server-backed, shared with the companion) ─────
time.get('/runs', async (c) => {
  const user = c.get('user')
  const rows = await db.select().from(clockTimerRuns)
    .where(eq(clockTimerRuns.userId, user.id))
    .orderBy(asc(clockTimerRuns.createdAt))
  return c.json({ runs: rows })
})

time.post('/runs', async (c) => {
  const user = c.get('user')
  const body = await c.req.json().catch(() => ({}))
  const durationSec = int(body.durationSec, 1, 24 * 3600)
  if (durationSec === null) return c.json({ error: 'durationSec required' }, 400)

  const now = new Date()
  const id = crypto.randomUUID()
  await db.insert(clockTimerRuns).values({
    id, userId: user.id,
    label: str(body.label, 80) ?? 'Timer',
    tone: str(body.tone, 200) ?? 'builtin:beacon',
    toneName: str(body.toneName, 120),
    announce: bool(body.announce, true),
    durationSec,
    endsAt: Date.now() + durationSec * 1000,
    paused: false,
    remainingMs: durationSec * 1000,
    createdAt: now,
  })
  const [row] = await db.select().from(clockTimerRuns).where(eq(clockTimerRuns.id, id))
  return c.json({ run: row })
})

time.patch('/runs/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  const [existing] = await db.select().from(clockTimerRuns)
    .where(and(eq(clockTimerRuns.id, id), eq(clockTimerRuns.userId, user.id)))
  if (!existing) return c.json({ error: 'Not found' }, 404)

  const body = await c.req.json().catch(() => ({}))
  const patch: Partial<typeof clockTimerRuns.$inferInsert> = {}
  // Pause: freeze remaining. Resume: re-derive endsAt from remaining.
  if (typeof body.paused === 'boolean' && body.paused !== existing.paused) {
    if (body.paused) {
      patch.paused = true
      patch.remainingMs = Math.max(0, existing.endsAt - Date.now())
    } else {
      patch.paused = false
      patch.endsAt = Date.now() + existing.remainingMs
    }
  }
  const label = str(body.label, 80); if (label) patch.label = label
  if (Object.keys(patch).length === 0) return c.json({ run: existing })

  await db.update(clockTimerRuns).set(patch).where(eq(clockTimerRuns.id, id))
  const [row] = await db.select().from(clockTimerRuns).where(eq(clockTimerRuns.id, id))
  return c.json({ run: row })
})

time.delete('/runs/:id', async (c) => {
  const user = c.get('user')
  const id = c.req.param('id')
  await db.delete(clockTimerRuns).where(and(eq(clockTimerRuns.id, id), eq(clockTimerRuns.userId, user.id)))
  return c.json({ ok: true })
})
