// AUTO-GENERATED from frontend StationArt.tsx. Do not edit by hand.
// Maps a station's name/category to a watermark glyph key (see stationIcons.generated.ts).

const NAME_ICONS: [RegExp, string][] = [
  [/retro gaming|classic game/, 'discFilled'],
  [/8-?bit|chiptune/, 'boltFilled'],
  [/video game remix|game remix/, 'headphonesFilled'],
  [/modern game soundtrack|cinematic game/, 'starFilled'],
  [/vaporwave/, 'moonFilled'],
  [/video game|gaming|jrpg|rpg|nintendo|playstation|arcade/, 'deviceGamepad2Filled'],
  [/bond\b|james bond|spy thriller/, 'diamondFilled'],
  [/tarantino|needle.?drop|cult film|exploitation/, 'flameFilled'],
  [/western|spaghetti western|outlaw film/, 'guitarPickFilled'],
  [/horror|spooky|halloween|scary|slasher/, 'ghostFilled'],
  [/sci-?fi|space opera|extraterrestrial|alien invasion/, 'ufoFilled'],
  [/superhero|marvel|dc comics|action movie/, 'boltFilled'],
  [/rom-?com|romcom|romantic comedy/, 'heartFilled'],
  [/training montage|sports film/, 'barbellFilled'],
  [/80s.*movie|movie.*80s/, 'discFilled'],
  [/epic.*score|film score|movie score|cinema score|hans zimmer|john williams/, 'starFilled'],
  [/movie|cinema|film|soundtrack|montage/, 'playerPlayFilled'],
  [/anime|studio ghibli|shonen/, 'worldFilled'],
  [/broadway|musical|showstopper|stage show|cabaret/, 'microphoneFilled'],
  [/disney channel|dcom/, 'sparklesFilled'],
  [/disney|pixar|dreamworks|animated film|animated movie/, 'sparklesFilled'],
  [/nickelodeon|rugrats|spongebob|hey arnold/, 'confettiFilled'],
  [/cartoon network|toonami|adult swim/, 'boltFilled'],
  [/saturday morning|after school cartoon/, 'sunFilled'],
  [/sitcom|comedy show|sketch/, 'confettiFilled'],
  [/tv theme|television theme|theme song|show theme/, 'discFilled'],
  [/tv|cartoon|nick\b/, 'deviceTvFilled'],
  [/hip-?hop|boom bap|golden age hip/, 'headphonesFilled'],
  [/trap|\brap\b|drill|mumble/, 'headphonesFilled'],
  [/new jack swing/, 'discFilled'],
  [/motown|neo-?soul/, 'microphoneFilled'],
  [/gospel|spiritual|choir/, 'microphoneFilled'],
  [/r&b|rnb|contemporary r/, 'heartFilled'],
  [/blues|delta blues|chicago blues/, 'microphoneFilled'],
  [/funk|p-?funk|parliament/, 'microphoneFilled'],
  [/soul\b|soul music/, 'microphoneFilled'],
  [/jazz age|roaring 20s|ragtime/, 'glassFullFilled'],
  [/big band|swing|dixieland/, 'confettiFilled'],
  [/bebop|hard bop|cool jazz|jazz fusion|free jazz/, 'microphoneFilled'],
  [/smooth jazz|lounge jazz|cocktail jazz|dinner jazz/, 'glassFullFilled'],
  [/bossa nova|latin jazz|afro-?cuban jazz/, 'worldFilled'],
  [/jazz/, 'glassFullFilled'],
  [/opera|aria|bel canto/, 'microphoneFilled'],
  [/baroque|renaissance music|early music/, 'crownFilled'],
  [/classical|orchestr|composer|symphony|concerto|chamber/, 'starFilled'],
  [/bluegrass|banjo|appalachian|string band/, 'guitarPickFilled'],
  [/outlaw country|country|honky|tonk|americana/, 'guitarPickFilled'],
  [/campfire|coffeehouse|camp songs/, 'campfireFilled'],
  [/folk|acoustic/, 'campfireFilled'],
  [/singer-?songwriter|indie folk/, 'featherFilled'],
  [/psychedelic rock|acid rock|space rock|krautrock/, 'alienFilled'],
  [/prog(ressive)? rock|art rock|math rock|concept album/, 'boltFilled'],
  [/glam rock|glam metal|hair metal/, 'diamondFilled'],
  [/surf rock|beach rock/, 'sunFilled'],
  [/yacht rock/, 'speedboatFilled'],
  [/rockabilly|doo-?wop|50s rock|sock hop/, 'discFilled'],
  [/nu-?metal|djent|post-?metal/, 'flameFilled'],
  [/punk rock|hardcore punk|emo|post-?punk/, 'flameFilled'],
  [/grunge|noise rock|shoegaze/, 'flameFilled'],
  [/garage rock/, 'flameFilled'],
  [/britpop|indie pop|jangle pop|dream pop/, 'headphonesFilled'],
  [/ska\b|rocksteady/, 'worldFilled'],
  [/southern rock|swamp rock|bayou/, 'guitarPickFilled'],
  [/stadium|arena rock|power ballad/, 'barbellFilled'],
  [/heavy metal|thrash|death metal|black metal/, 'flameFilled'],
  [/metal|rage|mayhem|headbang/, 'flameFilled'],
  [/alternative rock|alt-?rock/, 'guitarPickFilled'],
  [/indie rock|college rock/, 'headphonesFilled'],
  [/rock\b/, 'guitarPickFilled'],
  [/ambient|drone|new age|soundscape|atmospheric/, 'moonFilled'],
  [/trance|psy-?trance|goa/, 'alienFilled'],
  [/drum.?and.?bass|dnb|jungle|breakbeat/, 'boltFilled'],
  [/deep house|tech house|house music|garage house/, 'confettiFilled'],
  [/techno|industrial techno|ebm/, 'boltFilled'],
  [/synthwave|retrowave|outrun/, 'boltFilled'],
  [/synth-?pop|electropop|new wave/, 'boltFilled'],
  [/edm|electronic dance|big room|festival edm/, 'confettiFilled'],
  [/electronic|synth|pulse/, 'boltFilled'],
  [/disco fever|disco ball|glitter/, 'globeFilled'],
  [/disco|dancefloor|boogie|funky house/, 'confettiFilled'],
  [/party|club night|festival/, 'confettiFilled'],
  [/karaoke|pub night|sing.?along/, 'beerFilled'],
  [/k-?pop|kpop/, 'starFilled'],
  [/j-?pop|city pop|japanese pop/, 'worldFilled'],
  [/reggaeton|reggaetón|salsa|cumbia|merengue|bachata/, 'confettiFilled'],
  [/latin.*party|latin.*dance|party.*latin/, 'confettiFilled'],
  [/latin heat|latin fire/, 'flameFilled'],
  [/latin\b|latin pop|latin rock/, 'worldFilled'],
  [/bollywood|desi|bhangra|hindi film/, 'sparklesFilled'],
  [/afrobeats|afropop|highlife|juju/, 'sunFilled'],
  [/reggae|dancehall|dub|caribbean/, 'sunFilled'],
  [/celtic|irish|scottish|welsh/, 'guitarPickFilled'],
  [/tropical|island vibes/, 'sunFilled'],
  [/global|world music/, 'worldFilled'],
  [/dinner party|dinner music|supper club|cocktail hour|wine and/, 'glassFullFilled'],
  [/love song|date night|romance|sensual|wedding|valentines/, 'heartFilled'],
  [/heartbreak|breakup|sad songs|melancholy|crying/, 'heartBrokenFilled'],
  [/pride|empowerment|feminist|girl power/, 'starFilled'],
  [/sleep|lullaby|bedtime/, 'moonFilled'],
  [/calm|meditat|yoga|zen|mindful/, 'sparklesFilled'],
  [/rain|rainy|storm/, 'cloudFilled'],
  [/feels|emotional|introspective/, 'moonFilled'],
  [/happy|joy|upbeat|cheerful/, 'sunFilled'],
  [/good times|feel-?good|vibes|positive/, 'sunFilled'],
  [/workout|pump up|gym|run\b|running|sport/, 'barbellFilled'],
  [/hiking|mountain|outdoor|trail/, 'mountainFilled'],
  [/confidence|boss|hustle|grind|motivat/, 'barbellFilled'],
  [/focus|deep work|study|productivity|coding/, 'sparklesFilled'],
  [/lo-?fi|chill study|study beats/, 'moonFilled'],
  [/relax|chill out|mellow/, 'moonFilled'],
  [/cooking|chef|kitchen|baking|foodie/, 'chefHatFilled'],
  [/coffee|morning routine|wake up|sunrise|cafe|café/, 'mugFilled'],
  [/road ?trip|driving|highway/, 'carFilled'],
  [/summer|beach|\bsun\b|sunshine|surf/, 'sunFilled'],
  [/dream|dreamy/, 'moonFilled'],
  [/christmas|xmas/, 'christmasTreeFilled'],
  [/holiday|festive|gift|winter holiday/, 'giftFilled'],
  [/british invasion/, 'guitarPickFilled'],
  [/flower power|hippie/, 'flowerFilled'],
  [/psychedelic 60|summer of love/, 'flowerFilled'],
  [/golden oldi|50s gold/, 'crownFilled'],
  [/\b40s\b/, 'crownFilled'],
  [/\b50s\b/, 'crownFilled'],
  [/\b60s\b|sixties/, 'flowerFilled'],
  [/\b70s\b|seventies/, 'globeFilled'],
  [/\b80s\b|eighties/, 'boltFilled'],
  [/\b90s\b|nineties/, 'guitarPickFilled'],
  [/\b2000s\b|y2k|noughties/, 'headphonesFilled'],
  [/\b2010s\b/, 'boltFilled'],
  [/nostalgia|throwback|oldies|golden age|classic era|retro|vintage pop/, 'discFilled'],
  [/greatest hits|best of|essential|definitive|ultimate|all-?time/, 'awardFilled'],
  [/classic\b|timeless|legendary|iconic/, 'crownFilled'],
  [/viral|trending|top songs|top 40|charts|today|now|fresh|new music/, 'discFilled'],
  [/hits\b/, 'discFilled'],
]

const CAT_ICONS: Record<string, string> = {
  'Featured': 'starFilled',
  'Genres': 'discFilled',
  'Decades': 'discFilled',
  'Eras': 'discFilled',
  'Moods': 'heartFilled',
  'Activities': 'barbellFilled',
  'Movies': 'playerPlayFilled',
  'TV & Cartoons': 'deviceTvFilled',
  'Gaming': 'deviceGamepad2Filled',
  'Global': 'worldFilled',
  'Classics': 'crownFilled',
  'Themed': 'sparklesFilled',
}

export function stationGlyphKey(name: string, category: string | null): string {
  const n = name.toLowerCase()
  for (const [re, key] of NAME_ICONS) if (re.test(n)) return key
  if (category && CAT_ICONS[category]) return CAT_ICONS[category]!
  return 'discFilled'
}
