import {
  Anchor,
  Armchair,
  Banknote,
  Beer,
  Bike,
  Briefcase,
  Brush,
  Bus,
  Camera,
  Car,
  Church,
  Cigarette,
  Clapperboard,
  Coffee,
  Cpu,
  Croissant,
  Cross,
  Dumbbell,
  Flag,
  Flame,
  Flower,
  Footprints,
  Fuel,
  Gem,
  Gift,
  Glasses,
  Hammer,
  Home,
  Hospital,
  Hotel,
  IceCream,
  Info,
  Landmark,
  Library,
  Mail,
  MapPin,
  Music,
  ParkingSquare,
  Palette,
  PawPrint,
  Pill,
  Plane,
  Sandwich,
  Scale,
  School,
  Scissors,
  Shield,
  Shirt,
  ShoppingBag,
  ShoppingCart,
  Smartphone,
  Sprout,
  Stethoscope,
  Store,
  Tent,
  Theater,
  Train,
  Trees,
  Trophy,
  Users,
  Utensils,
  Volleyball,
  Wine,
  Wrench,
  Zap,
  type LucideIcon,
} from "lucide-react";

export { poiIconSvgInner } from "./poi-icon-nodes";

export const POI_LUCIDE_ICON: Record<string, LucideIcon> = {
  restaurant: Utensils,
  cafe: Coffee,
  fast_food: Sandwich,
  ice_cream: IceCream,
  bar: Wine,
  pub: Beer,
  wine: Wine,
  bakery: Croissant,
  grocery: ShoppingCart,
  shop: ShoppingBag,
  convenience: ShoppingCart,
  pharmacy: Pill,
  bank: Banknote,
  atm: Banknote,
  gas: Fuel,
  charging: Zap,
  parking: ParkingSquare,
  school: School,
  hospital: Hospital,
  clinic: Stethoscope,
  library: Library,
  museum: Landmark,
  gallery: Palette,
  hotel: Hotel,
  lodging: Hotel,
  transit_bus: Bus,
  transit_train: Train,
  transit_subway: Train,
  airport: Plane,
  park: Trees,
  place_of_worship: Church,
  post: Mail,
  police: Shield,
  fire_station: Flame,
  salon: Scissors,
  hairdresser: Scissors,
  barber: Scissors,
  dentist: Stethoscope,
  laundry: Shirt,
  post_office: Mail,
  gas_station: Fuel,
  beauty: Brush,
  clothing: Shirt,
  shoes: Footprints,
  jewelry: Gem,
  optician: Glasses,
  vet: PawPrint,
  pet: PawPrint,
  electronics: Cpu,
  phone_shop: Smartphone,
  furniture: Armchair,
  hardware: Hammer,
  gardencenter: Sprout,
  florist: Flower,
  car_dealer: Car,
  auto_repair: Wrench,
  bike: Bike,
  tourist_info: Info,
  attraction: Camera,
  camp: Tent,
  marina: Anchor,
  gym: Dumbbell,
  sports: Volleyball,
  golf: Flag,
  bowling: Trophy,
  cinema: Clapperboard,
  theatre: Theater,
  nightclub: Music,
  government: Landmark,
  community_centre: Users,
  funeral: Cross,
  marketplace: Store,
  office_generic: Briefcase,
  lawyer: Scale,
  music: Music,
  tobacco: Cigarette,
  gift: Gift,
  home: Home,
  default: MapPin,
};

export function poiLucideIcon(iconId: string | null | undefined): LucideIcon {
  if (!iconId) return MapPin;
  return POI_LUCIDE_ICON[iconId] ?? MapPin;
}
